### ISSUE TITLE
New targeting bits for standard stars

### ISSUE THREAD

**Issue by geordie666** [desihub/desispec#1086]
In https://github.com/desihub/desitarget/pull/669 I added three new standard star classes:
```
    - [GAIA_STD_FAINT,      33, "Standard stars for dark/gray conditions",   {obsconditions: DARK|GRAY}]
    - [GAIA_STD_WD,         34, "White Dwarf stars",                         {obsconditions: DARK|GRAY|BRIGHT}]
    - [GAIA_STD_BRIGHT,     35, "Standard stars for BRIGHT conditions",      {obsconditions: BRIGHT}]
```
Crucially, these are added to the `mws_mask` (and `sv1_mws_mask`), not to `desi_mask`:

https://github.com/desihub/desitarget/blob/22229d03115ec1804fa6e5464d221c1bb97bf22d/py/desitarget/sv1/data/sv1_targetmask.yaml#L140-L142

These are analogues of the already-defined standards, but based _only_ on Gaia to facilitate observations outside of the Legacy Surveys imaging footprint

**Comment by sbailey** [comment]
`desispec.fluxcalibration.isStdStar` is the place to add these bits.  Since this takes the fibermap as input, and the fibermap has (SV1_)MWS_TARGET I don't think this is a fundamental problem here, but it is the first time that core pipeline "what should I do with this target" leaks out of the (SV1_)DESI_TARGET column, so I'm highlighting that, e.g. are there other places (qproc? nightwatch?) that might expect to be able to derive ELG/LRG/QSO/MWS/BGS/STD/SKY only from (SV1_)DESI_TARGET?

@geordie666 if these bits are set but no other MWS bits are set, is the (sv1_)desi_mask MWS_ANY bit set?  We tend to view that bit as meaning "some MWS science target bit is set" rather than "some bit in MWS_TARGET is set".  Maybe these are all MWS science targets too, but we'll need to consider if this has impact on bookkeeping.

**Comment by geordie666** [comment]
I currently _do_ set the ``MWS_ANY`` bit if the bits for the Gaia standards are set: 

https://github.com/desihub/desitarget/blob/22229d03115ec1804fa6e5464d221c1bb97bf22d/py/desitarget/cuts.py#L2395-L2407

I don't have to, though, I can change that back. We've only run a very limited set of tiles for the M31 dedicated program with this set-up so far.

Let me know if you'd prefer ``MWS_ANY`` _not_ to be set purely for Gaia standards.

**Comment by sbailey** [comment]
Let's leave MWS_ANY set for these targets.

**Comment by sbailey** [comment]
Reopening.  PR #1105 added the GAIA standard star bits to `desispec.fluxcalibration.isStdStar`, but now the problem is that these targets don't have FLUX_G/R/Z used for color cuts and absolute normalization.  An example tile to study is 80715 observed on 20210115 exposures 72498-72500, using this test command:
```
cd /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20210115/
desi_fit_stdstars --delta-color 0.1 \
    --frames 00072498/frame-?2-*.fits 00072499/frame-?2-*.fits 00072500/frame-?2-*.fits \
    --skymodels 00072498/sky-?2-*.fits 00072499/sky-?2-*.fits 00072500/sky-?2-*.fits \
    --fiberflats /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20210115/fiberflatnight-?2-20210115.fits \
    --starmodels /global/cfs/cdirs/desi/spectro/templates/basis_templates/v3.2/stdstar_templates_v2.2.fits \
    --outfile $SCRATCH/stdstars-2-00072498.fits
```
That ends with a misleading message "ValueError: no STD star found in fibermap" but tracing the code, it's actually that there are GAIA standards in the file but they are failing the basic quality checks on magnitude ranges, and would fail later code on color cuts anyway.

@segasai could you take a look at this and make updates to support GAIA standards, while not breaking the current behavior for normal standards?  e.g. the color filter is an optimization to only check models with colors close to the photometric colors so we don't want to just completely turn that off.

**Comment by segasai** [comment]
So would we want to preselect based based on Gaia BP-RP or G-RP instead of g-r, or just not do any preselection ? 
I assume at first we would just skip preselection for Gaia only stds (because the models would need to have BP/RP/G computed for example), but implement it later ?

**Comment by sbailey** [comment]
It is way slower to fit all models instead of just the ones with approximately right colors, so I think we do want some sort of color pre-filtering, for which you could use an approximate transform from Gaia colors to Legacy Survey colors.  However, after selecting the best model for each star, it is normalized to the r-band magnitude (see `desispec.scripts.stdstars lines 450-470).  So you'll also need to replace that with a Gaia magnitude (or a really good transform?) if FLUX_R isn't available.  i.e. you'll need to calculate Gaia model magnitudes in at least one filter anyway.

However, continuing down the rabbit hole, we currently use the [speclite](https://github.com/desihub/speclite) package to coordinate filters and calculating magnitudes, and that doesn't have Gaia filters yet.  @dkirkby is the primary maintainer of that package, but it is in desihub so anyone can contribute the Gaia filters to it.

**Comment by moustakas** [comment]
> However, continuing down the rabbit hole, we currently use the speclite package to coordinate filters and calculating magnitudes, and that doesn't have Gaia filters yet. @dkirkby is the primary maintainer of that package, but it is in desihub so anyone can contribute the Gaia filters to it.

And there's even an open ticket https://github.com/desihub/speclite/issues/40!

**Comment by segasai** [comment]
I've made a PR of Gaia passbands https://github.com/desihub/speclite/pull/62

**Comment by segasai** [comment]
Given the gaia passbands are now parts of speclite I've made a branch https://github.com/desihub/desispec/tree/gaiastds_v2 where I try to synthesize the Gaia colors in stdstars

**Comment by segasai** [comment]
Here is a new PR https://github.com/desihub/desispec/pull/1109

It successfully calibrates the M31 data with this command
desi_fit_stdstars --color 'GAIA-BP-RP' --delta-color 0.1     --frames 00072498/frame-?2-*.fits 00072499/frame-?2-*.fits 00072500/frame-?2-*.fits     --skymodels 00072498/sky-?2-*.fits 00072499/sky-?2-*.fits 00072500/sky-?2-*.fits     --fiberflats /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20210115/fiberflatnight-?2-20210115.fits     --starmodels /global/cfs/cdirs/desi/spectro/templates/basis_templates/v3.2/stdstar_templates_v2.2.fits     --outfile $SCRATCH/stdstars-2-00072498.fits
