### ISSUE TITLE
dashboard: filter by OBSTYPE and arc EXPTIME

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1141]
Add options to desi_dashboard:
* filter by OBSTYPE, with default including ARC,FLAT,SCIENCE but not ZERO,OTHER,DARK,TEST
* filter by ARC EXPTIME

e.g. for the Cascades run we are only processing SCIENCE, FLAT, and ARCs with EXPTIME <= 5.1 sec, so it would be helpful for the Cascades dashboard to ignore the 30s ARCs and other flavors so that we don't have red warnings for exposures we aren't trying to process.

This could be updated in master even after the final tags for release 21.2 / Cascades.

**Comment by akremin** [comment]
I agree with the above. Rather than reinventing these selection cuts, the dashboard code could read in the processing table, which by definition specifies only the exposures that are actually being processed. You still need to read in the exposure table for other information, this would be in addition to that. There is also a difference in format, in that the processing table is one row per _job_ as opposed to one row per _exposure_. This means EXPID is an array in the processing table and that an EXPID can appear on multiple different rows.

All that is to say, you could: (1) load in the processing table, (2) add all "EXPID" array elements to a set(), and (3) check to see if your exposure table entry EXPID is in that set before including it in the dashboard HTML table.

**Comment by sbailey** [comment]
Implented with @akremin's suggestion of filtering by processing status rather than command line options in PR #1152, thanks; closing.
