### ISSUE TITLE
TSNR: apply Galactic dust extinction

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1174]
Need to apply the Galactic dust extinction to the signal.

**Comment by michaelJwilson** [comment]
This seems a simple one, I can handle in dustytsnr.  Do you want to add the spectral arm coefficients to desiutil.dust, or approximate them by the imaging bands?

**Comment by julienguy** [comment]
you can apply the extinction to the delta_f as a function of wavelength as in https://github.com/desihub/desispec/blob/3699f70a57afff58d2c843f2741af16ef91d70da/py/desispec/scripts/stdstars.py#L71

**Comment by michaelJwilson** [comment]
I pushed this to dustytsnr.  It seems simple enough to vet by itself, otherwise happy to run some test tiles for the effect.  We can do one PR per issue, or try to clean up multiple of the ticket in one.  Whatever your preference.

**Comment by sbailey** [comment]
Thanks @michaelJwilson let's do one PR per issue so that questions about one set of changes (e.g. the ongoing conversation over in #1175 about TSNR and fiberfrac/seeing) don't block another set of useful changes from getting merged.  It also distinguishes what changes come from dust updates vs. seeing updates, etc.

**Comment by michaelJwilson** [comment]
Sounds good. I'll wait for @julienguy to say whether this is simple enough to go in, or needs vetting with some test tiles. If the latter, we should probably discuss how to best set up some development suite or similar. It seems there's enough material for a discussion for the data call, if the agenda isn't otherwise full.

**Comment by julienguy** [comment]
I think this is simple enough to go in. Please open a PR.

**Comment by julienguy** [comment]
solved
