### ISSUE TITLE
TSNR: account for relative change of fiber loss with seeing

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1175]
- the fiber aperture loss from point source is automatically accounted for with the calibration vectors in the computation of TSNR
- a typical ratio of fiber aperture loss between extended objects and point source is already considered.
- but the variation of this ratio with seeing is ignored. including this would be an improvement.

**Comment by michaelJwilson** [comment]
Thoughts on this?  E.g. I can put a fit to below under /data (derived from Aaron's GFA files), and use it as a lookup for given seeing - after normalizing to unity for the legacy 1.3'' given we account for this already.  But how to pull in Aaron's PSF FWHM for a given exp.?  These are 'offline' so we can't assume they're available on a given night, as I understand it.   

![image](https://user-images.githubusercontent.com/6034066/110267139-0a428e80-7f74-11eb-9e18-ebad8b303fff.png)

**Comment by dkirkby** [comment]
You will be able to read FFRAC from the ETC json file written with the raw data starting any night now.

**Comment by michaelJwilson** [comment]
I'm guessing we want to support something as close to the tracer FFRACs defined here:  
https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed

which likely requires working from something more fundamental than this raw ETC FFRAC, unless you plan on supporting something similar.  There's also how we handle past exposures. 

These aren't obvious to me so I'll wait for further input.

**Comment by djschlegel** [comment]
This this is per-object, so you could recompute FIBERFLUX for each object given its morphology and the actual seeing.  It would then be a function of MORPHTYPE,SERSIC,SHAPE_R,SHAPE_E1,SHAPE_E2.  @dstndstn may be able to provide an extraction of that from the tractor code.

**Comment by dkirkby** [comment]
The ETC will provide FFRAC calculated for stars as well as for nominal ELG or BGS profiles.

If you want to calculate per-object FFRAC, you could start with the ETC's per-exposure model of the PSF then convolve this with per-object profiles.

Regarding past data, ETC results are available for all exposures starting Dec 2020.

**Comment by michaelJwilson** [comment]
Isn't it per fiber, rather than per object?  I.e. we're stepping away from the z success for the target that was actually on the fiber and solving for some typical target instead, e.g. those at the flux limit.  The distinction with the Depths, EFFTIMES etc. is just the better resolution on data quantities, e.g. fiber throughput, spectral range that matters etc. 

> nominal ELG or BGS profiles.
I think we also want LRG & QSO, to step beyond just the ETC definition of 'completed' to actual completeness.   

@dkirkby can you point me to an example ETC file, and any docs. that exist.

**Comment by michaelJwilson** [comment]
Sounds good.  I'll wait for @julienguy to say whether this is simple enough to go in, or needs vetting with some test tiles.  If the latter, we should probably discuss how to best set up some development suite or similar.  It seems there's enough material for a discussion for the data call, if the agenda isn't otherwise full.

**Comment by julienguy** [comment]
Mike let's talk offline. There is the code to compute the fiberfrac in desimodel as a function of seeing, fiber position offset, galaxy shape. We can normalize it on the ETC values.

**Comment by michaelJwilson** [comment]
ok, let me know.  I know the code you mean (I had it in my original tsnr scripts) but strikes me this is probably stepping too far away from what @djschlegel is doing in the efftime.  I'd imagine we'd want them to be the same, where possible.

**Comment by julienguy** [comment]
I don't understand your point. Let's talk offline and not use github issues as a chat.

**Comment by julienguy** [comment]
this is done
