### ISSUE TITLE
desi_tile_redshifts bug with partial inputs

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1194]
I've already found a bug with my shiny new desi_tiles_redshifts: e.g. for tile 80607 it is checking whether it should try generating spectra with:
```
ls exposures/20201218/00068662/cframe-[brz]$SPECTRO-00068662.fits exposures/20201218/00068663/cframe-[brz]$SPECTRO-00068663.fits exposures/20201218/00068664/cframe-[brz]$SPECTRO-00068664.fits exposures/20201218/00068666/cframe-[brz]$SPECTRO-00068666.fits &> /dev/null
if [ $? -eq 0 ]; then
    ...
```
That `ls` returns a non-zero exitcode if _any_ of those globs don't match, instead of the intended check that _all_ of them don't match.  The result is that if a petal is missing for any exposure, that petal isn't grouped at all, instead of grouping what it can find.

I think the solution is to `ls` and count the length of the outputs and check that there are more than zero.

**Comment by sbailey** [comment]
Branch "tile_redshifts2" has a fix for the case where cframes are missing from some but not all exposures, which can legitimately occur if a petal is disabled one night but not others.

However, this raises a different fragility, where `desi_tile_redshifts` would plow ahead and make redshifts even if missing some inputs that should have been there.  I'd appreciate @akremin opinion (or anyone else's...) on whether that is better or worse.

Normally I prefer "fail early and fix the underlying problem", but in this case I'm not sure we have a fix.  If the entire spectrograph is marked as bad for an exposure then the python side could somehow communicate that to the bash side (tedious but possible in principle with some additional refactoring).  But if we wanted to do what we did in cascades and process disabled petals through skysub, we don't currently have a way of indicating that the cframes are supposed to be missing, but only for that petal.

I don't like the "plow ahead" aspect of tile_redshifts2, but I don't see another quick fix to get beyond the blocking factor for using `bin/desi_tile_redshifts` when some cframes are legitimately missing.  @akremin thoughts?

**Comment by akremin** [comment]
I think for the time being the only path forward is the "plow ahead" route. One thing you could do is print those out to the log with prominent error messages that we get in the habit of checking as part of routine operation. (For the record I didn't look at your PR, so you probably already do this).

I agree with you that it's sub-optimal, but I think we have to live with it for now. The petal availability is very chaotic in SV1, so we need this fix for the tiles with exposures on multiple nights. 

I am developing scripts for vetting the generated files for a production, which could be run prior to submitting these redshift scripts to ensure everything we wanted is there. But the timeline I was working under was the Denali run, not the 0.1% survey. So that script doesn't exist in a PR today and won't help with the 0.1% next week unless I move that to the top of my priority list.
