### ISSUE TITLE
Positioners on bad/disabled petals not flagged as bad

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1229]
I'm seeing multiple cases where a petal has failed to get positioners on target, but the positioners are not getting FIBERSTATUS != 0 flags in the fibermap and thus the pipeline is trying to use them and sometimes accidentally "succeeding".  This is problematic when coadding data across nights were one one night it was genuinely good and another night it was silently bad and terribly calibrated.  We're either mis-interpreting the flag bits in the coordinates files, and/or we need to augment those bits with our own cuts on DELTA_X/DELTA_Y.

Example from 20210317/00080825:

![image](https://user-images.githubusercontent.com/218471/113467057-565ae480-93f5-11eb-8b1d-536a2c75d0be.png)

Nightwatch posacc plots like [this](https://nightwatch.desi.lbl.gov/20210317/00080825/qa-camfiber-00080825-posacc_plots.html) are useful for scanning through these cases.

Action items:
  * Short term as part of Denali cleanup:
    * systematically identify failed petals using (DELTA_X, DELTA_Y)
    * flag them as bad in the exposures tables
    * remove any accidentally successful cframes and pernight spectra, coadds, redshifts
    * do this before generating cumulative and perexp spectra, coadds, redshifts
  * Longer term for Everest:
    * Update fibermap logic so that positioners that aren't on target are properly flagged with FIBERSTATUS != 0
    * Update exposure_table logic so that if the number of bad positioners on a petal is above some threshold (250?), discard the entire petal for that exposure.

**Comment by tskisner** [comment]
@sbailey , just checking in- does this FIBERSTATUS in the fibermap get propagated from the fiberassign file for the exposure?  I am guessing it must at least pass through the plate control software since some fiber moves might be rejected and set to unassigned.  For reference the fiberassign bit definitions are here:

https://github.com/desihub/fiberassign/blob/06240acab043eb3d8ffbe31ab29a29d56a031f3f/src/hardware.h#L24-L28

The bits are set when writing out the fiberassign files here:

https://github.com/desihub/fiberassign/blob/06240acab043eb3d8ffbe31ab29a29d56a031f3f/py/fiberassign/assign.py#L433-L444

And positioners not in that dictionary are marked as unassigned.  The dictionary of assignments for a given tile comes from here:

https://github.com/desihub/fiberassign/blob/06240acab043eb3d8ffbe31ab29a29d56a031f3f/src/assign.cpp#L117

Which is a genuine C++ `std::map` containing only assigned locations.  The fact that this only contains assigned locations is something that is used extensively in the C++ code to determine what positioners are assigned, so I believe it really does contain only assigned locations when passed to python.

Just so that I understand the symptom, you are saying that some targets have FIBERSTATUS == 0, but then also have TARGETID < 0, correct?

**Comment by sbailey** [comment]
@tskisner the FIBERSTATUS starts with the bits set by fiberassign, but then is augmented by assemble_fibermap using flags in the coordinates*.fits files from ICS/platemaker indicating what actually happened in the positioning loop, using logic here:

https://github.com/desihub/desispec/blob/e9cb3b8ec917e52650cdcc842bde39fada325d48/py/desispec/io/fibermap.py#L492

The issue I'm highlighting isn't from fiberassign, but rather an entire petal of fibers that aren't on target, but we're still passing most of them forward as FIBERSTATUS=0 as if they were good.  We're either missing a bit from ICS/platemaker/coordinates (not fiberassign) that we're failing to propagate, and/or we need to add our own positioning check.

We might even consider having different criteria for science targets vs. standard stars for how well we require the positioning to be for them to count as "good".

**Comment by sbailey** [comment]
fixed in PR #1235 where we now make an explicit cut on `sqrt(DX_n**2 + DY_n**2)`.
