### ISSUE TITLE
MJD in tsnr file

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1255]
Feel free to close with WONTFIX.  But looking at the survey margins now, I really want to be able to get things like twilight and the moon phase to correlate with the tsnr sky brightness.  But it's annoying to do this because there's no MJD tabulated, just NIGHT and EXPID.  It would be nice if MJD were tabulated.

OTOH, it only took 10 min to trawl this out of all the headers.

**Comment by schlafly** [comment]
Related request from the instrument call today: ra/dec in the tiles.csv file.  Alternatively available via matching to the tile file from the survey ops product, but perhaps easier if one didn't have to read the appropriate tile file depending on the survey.

**Comment by sbailey** [comment]
These are both reasonable requests.

**tsnr-exposures.fits**: we're up to 40 columns, have well exceeded the original "tsnr" purpose of the filename, and still have more columns to add to make this a one stop shop.  Does someone have a curated comparison of all the different exposures lists that are floating around?  @schlafly in the meantime you should also be aware of the exposure_tables/YEARMM/exposure_table_YEARMMDD.csv files that could have saved you some header scraping pain.

**tiles.csv**: I'm wondering whether the spectro pipeline tiles.csv should start with the surveyops tiles file(s) and then add columns rather than picking and choosing which columns to propagate forward.

i.e. amidst all the other urgent items, I'm open to further evolving these files, but it would be helpful to review these for what we want them to be for the SVDA and try to make one bigger update to avoid trickling N>>1 individual requests.

**Comment by schlafly** [comment]
I think at the moment the tiles.csv file does not have a dependence on the surveyops/tiles-svX.ecsv files.  Maybe that's not true.  But I think it could be true that you get all the information from the fiberassign files and don't need to know about the survey planning files.  That was not the case before SV3 when we didn't have things like GOALTIME and SBPROF in the fiberassign files.

i.e., for my two cents, tiles.csv shouldn't care about surveyops/tiles*.ecsv.

I hear you that feature creep begets feature creep---it's only because every other column I need is in there that I want just one more column.

Anyway, this isn't urgent.

**Comment by geordie666** [comment]
> Related request from the instrument call today: ra/dec in the tiles.csv file. Alternatively available via matching to the tile file from the survey ops product, but perhaps easier if one didn't have to read the appropriate tile file depending on the survey.

Related to @schlafly's point, here. I just chatted with @sbailey about HEALPix-based redshifts and he convinced me that I _don't_ need the ra/dec in the tiles.csv file to perform the MTL loop. This is because I always need the `TARGET_RA`, `TARGET_DEC` for every `TARGETID`, so I can look up which HEALPixel a target is in without ever having to intersect the tiles and HEALPixels.

**Comment by schlafly** [comment]
Bringing this issue forward again in the context of updating tsnr.fits -> exposures.fits at @sbailey's request: I think it would be nice to add the following columns:
* MJD
* ra
* dec

**Comment by sbailey** [comment]
Added in PR #1348; will be used for final Everest tables.
