### ISSUE TITLE
COADD_FIBERMAP MEAN quantities for early cosmic split exposures.

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#1327]
Early cosmic split exposures  had the FIBER_X,FIBER_Y,DELTA_X,DELTA_Y,FIBER_RA,FIBER_DEC values set only for the first exposure and not the other ones.
As a result the MEAN quantities (MEAN_FIBER_X, ....) are incorrect because zero values are included in the average.
This issue was found in the development work of Stephen for the Everest data model but is also present in the daily reductions.
 
Example:
```
h=pyfits.open("/global/cfs/cdirs/desi/users/sjbailey/dev/coadd/tiles/cumulative/1/20210406/coadd-4-1-thru20210406.fits")
tid=h["COADD_FIBERMAP"].data['TARGETID'][0]
ii=(h["EXP_FIBERMAP"].data['TARGETID']==tid)
h["EXP_FIBERMAP"].data['FIBER_X'][ii]
array([231.508,   0.   ,   0.   ])
h["COADD_FIBERMAP"].data['MEAN_FIBER_X'][0]
77.169334
```

**Comment by sbailey** [comment]
Thanks for catching this.  Best would be if we could catch this in assemble_fibermap so that the per-exposure quantities are correct from the beginning.  Otherwise we could special-case excluding from the mean values that are exactly 0, but that is a bit of a hack.

**Comment by sbailey** [comment]
Update: this problem was already fixed upstream in assemble_fibermap, it just wasn't fixed at the time the daily prod was run and that was what I used as input for Everest fibermap testing.  In particular, if an exposure coordinates files doesn't have FIBER_X/Y etc. information, assemble_fibermap will look for immediately prior exposures of the same tile to get the information from the first exposure in the sequence.

I'll add a unit test to verify this in a PR that addresses #1288 (missing PLATE_RA, PLATE_DEC).  Closing this issue.
