### ISSUE TITLE
Data files not installed / usable

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#133]
When doing "python setup.py install --prefix=<blah>", the files in the data subdirectory are not installed.  At run time, the path to data is formed with

desispec_path = imp.find_module('desispec')[1]+'/../../'

Do we have a standard way of installing data files with setup.py, and obtaining the path to their installed location?

**Comment by weaverba137** [comment]
@tskisner, where exactly are you trying to install desispec?  Which version?  Any particular reason you're not using pip?  Can you use NERSC as a workaround?

**Comment by tskisner** [comment]
This was installing from a git checkout on edison, where I was manually installing harp, specex, desiutil, desisim, specter, and desispec.  So I guess the usual "python setup.py install --prefix=" command is not intended to be used like this?

**Comment by weaverba137** [comment]
Ah, OK.  All software DESI on NERSC should *only* be installed by desiInstall.  Can you explain further why you needed to manually install it?  This might be a use case that we've missed.

**Comment by tskisner** [comment]
ok, I guess this is just user error on my part.  I was not aware that I had to use desiutil / desiInstall to install a working software stack, and thought I could manually install development versions directly from the git checkouts.

Is it possible to do a "python setup.py develop --prefix=<blah>" to install links back to the live git checkouts?  Basically I'm trying to find the best workflow for "active hacking" on the packages.  If develop mode is supported, then I can just use that for this kind of workflow, and use desiInstall when installing static versions of things.

**Comment by weaverba137** [comment]
OK, again, just trying to establish the use case here.  At NERSC we already have git checkouts of desispec on cori and edison.  These can be accessed with `module load desispec/master`.  You should double-check, but I don't think anyone is actively using them, so you could probably do a git pull or git checkout in those.

However, more broadly, I think you may have stumbled on a dirty little secret, which is that neither pip nor `python setup.py install` will install directories *outside* of the package it is installing.  This is why all Python developers recommend putting data files *inside* the package directory.  In desispec's case it would involve moving the data directory to py/desispec/data.  The data can then be accessed using the `pkg_resources` module.

The reason that this is a dirty secret is that even though we have supported pip installs of DESI packages for work on laptops & other systems (*i.e.* anywhere that is not NERSC) for some time, I strongly suspect that nobody has ever actually used this feature very much.  Instead, most people, myself included, run code out of git checkouts, & with *those* the data directory is right there.

This most strongly affects desispec, desisim & specter.  specsim, in contrast, already has a data directory inside the package itself.  For desispec, desisim & specter, their data directories are not very big, & could be moved into the package itself quite easily, though specter's data directory is by far the largest of the three.

Finally, for technical completeness, desiInstall circumvents this problem by making a copy of the entire checkout or export into a versioned directory, *then* installing the Python package into that same directory.  You actually end up with two copies of the Python code this way, but the `PYTHONPATH` only points to one of them.

**Comment by tskisner** [comment]
I am actively working on the source in a branch.  So I definitely don't want to use some pre-installed version at NERSC.  Most python packages with a setup.py file support both the "install" target and also the "develop" target (which installs links back to the source tree).  When working on multiple packages, I usually use this "develop" target to install links to all packages to a common location, and then add that single place to PATH and PYTHONPATH.

From the rest of your comment, I guess all other DESI developers who are working on the code are working straight from the git checkouts, and just pointing PATH, PYTHONPATH, etc to point to the git checkout for each package, rather than installing these to a development location.

So I guess I'll follow the "DESI way" and do this too.

**Comment by weaverba137** [comment]
desispec/master is not "pre-installed", it is a git checkout.  You should be able to checkout a branch in there.

**Comment by dkirkby** [comment]
I generally use `python setup.py develop` on my laptop for DESI development.  Doesn't this still work at NERSC if you add the `--user` option?

**Comment by tskisner** [comment]
Now I'm really confused.  Are you suggesting that multiple developers actively hack on the same git checkout?  That doesn't make sense, so I must not understand something.  Every other software project I work on has a workflow like:  
1.  git clone the repo
2.  make branches as needed for active work
3.  build and install code (for compiled projects)
4.  OR install with develop target (for python projects)
5.  test code, change code, reinstall (for compiled projects).

**Comment by tskisner** [comment]
@dkirkby, I do use the develop target at NERSC (installing to a development prefix that I add to PATH and PYTHONPATH).  So that seems to work.  I guess the main point is that the install target should never be used, and that installation should only be done with desiInstall.  This is somewhat counter-intuitive, but I guess is a product of lots of other factors...

**Comment by weaverba137** [comment]
PS, back to the original report, that way of forming the path to the data directory is also not good.  We typically use environment variables for something like this.  In this case it would be `$DESISPEC/data`.

**Comment by tskisner** [comment]
Ok, we could close this issue, since "python setup.py install" is not supposed to work.  I guess separately we could clean up the path forming.

**Comment by weaverba137** [comment]
@sbailey, let's get your feedback on this before we close.

**Comment by sbailey** [comment]
PR #134 partially solves this, but as Ben noted in the comments, it isn't a long term solution.

Our install situation should be so straightforward and robust and documented that it doesn't generate long email discussions.  This isn't the case.  Situations like "python setup.py install" not working is just asking for trouble.  Install options that I know about:

### manually edit environment ###

    git clone https://github.com/desihub/desispec
    export PYTHONPATH=`pwd`/desispec/py:$PYTHONPATH
    export PATH=`pwd`/desispec/bin:$PATH
    export DESISPEC=`pwd`/desispec

This is effectively what I do, though I use module files to set the environment.  Julien does similar via a bash script that he sources.  This is non-standandard for an "install", but it works for pure python packages that don't use console_scripts or need to compile anything.

### python setup.py install ###

    git clone https://github.com/desihub/desispec
    cd desispec
    python setup.py install

(and variants involving `develop`, `--prefix`, or `--user`).  *This should work, and doesn't*, due to the problem of finding data files that don't live under the python source file tree.

Note: I haven't had good experiences with "python setup.py develop" because it hardcodes the current version into the installed script wrappers, and then if you `git pull` or swap to a different branch that changes the version, the installed scripts break.  I thought the whole point of `develop` was to be able to work from a live copy of the git clone while developing, and that just doesn't work if the version number changes.

### pip install ###

    pip install git+https://github.com/desihub/desispec.git@0.4.1#egg=desispec

When I originally requested to support pip install, what I meant was:

    pip install desispec

I hope the git+https stuff is just a temporary solution along the way.  It is possible that "pip install" is broken for the same reason that "python setup.py install" is broken.

### desiInstall ###

    #- At NERSC
    desiInstall desispec 0.4.1

This is a special case for installing our code into a standardized location at NERSC and configuring module files to match.  It isn't intended to support other locations or user development installs.

There are "master" versions of most products installed along side the tagged version; they are updated nightly as part of the cronjob integration tests.  They are *not* intended for developers to swap out to other branches for testing or do any live development there.

### Misc comments ###

We've been relying on SDSS-style package management where every package includes an environment variable defining where it is installed, and code can rely upon that environment variable being set to find companion data files.  This works for eups or modules, but is non-standard for normal installs of python packages and is generating confusion.

I see 3 options, none of which are very good:

1. continue to require setting an environment variable to be able to find data files.  i.e. don't support "python setup.py install" by itself.
2. put the data directory under the python code directory and include that in the install.
3. keep the data directory at the top level, have setup.py copy that into the code location if you install, and have code look in both locations as needed.

Keeping data underneath the python code tree seems crazy and wrong to me based upon decades of experience with coding best practices, but (2) might be the least evil.

And we need to document how new developers should get up and running.  Too many people are discovering how to do this by trial-and-error.

**Comment by julienguy** [comment]
I suggest we support only two installation modes :

- development : no copy of the file from the git clone
- production : done by desiInstall, with only a support for the NERSC
system, with a copy of the files

* for the development mode, I suggest we do not enforce a precise setup
tool but document one or several installation procedures, it can be a wiki
page.
* it turns out that indeed, guessing where the data directory is from the
source code path is fragile, so we might have to use environment variables,
set by desiInstall, and documented for the development mode.

julien

**Comment by weaverba137** [comment]
Comments:

1. All pip install does is setup.py install under the hood, so if one works, the other will too.
2. Doing `pip install desispec` as opposed to `pip install git+https://github.com/desihub/desispec.git@0.4.1#egg=desispec` requires that desispec can be found in a standard repository like http://pypi.python.org.  It doesn't *have* to be PyPI itself, just a repository that pip can communicate with.  I assumed that everyone was quite happy with the git+https method, so I've never researched this further.
3. Keeping data inside the Python code tree is not crazy if the data are absolutely critical to the code functioning *and* the data files *need* to be rigidly version controlled.  If the data are not critical or do not need to be rigidly version controlled, then data should be downloaded as needed from some some data server.  This is what astropy recommends, & their data infrastructure is patterned around this.  "Downloaded" can also mean "at some locations the data may live in a particular path on disk", which is how it would work at NERSC.

**Comment by sbailey** [comment]
Related: desisim has the same basic problem in targets.py:
```
        recombfile = resource_filename('desisim', os.path.join('..','..','data',
                                                               'recombination_lines.ecsv'))
        forbidfile = resource_filename('desisim', os.path.join('..','..','data',
                                                               'forbidden_lines.ecsv'))
        forbidmogfile = resource_filename('desisim', os.path.join('..','..','data',
                                                                  'forbidden_mogs.fits'))
```
This works fine if you have just added desisim/py to PYTHONPATH, but fails if you use "setup.py install" to copy it elsewhere.

**Comment by weaverba137** [comment]
I just noticed this comment about desisim.  That is actually an abuse of `resource_filename()`.  `resource_filename()` is used to find files *within* the actual Python package (in this case the py/desisim directory and subdirectories).

I'm surprised it works at all.  In any case this needs to be fixed, because it actually *shouldn't* work.

**Comment by moustakas** [comment]
Suggestions on how to do this correctly are welcome!  Should these files be in a (new) desisim/py/desisim/data directory, rather than in desisim/data ?

**Comment by weaverba137** [comment]
@moustakas, see desihub/desisim#115.

**Comment by sbailey** [comment]
Ben is dealing with this in other tickets for multiple products, so closing out this question.
