### ISSUE TITLE
Summer 2021 tiles to retire

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1354]
The following tiles were only partially completed at the start of the summer 2021 shutdown.  The survey ops team has retired these tiles and will redo these locations with different TILEIDs and new fiberassignments with the newly calibrated focal plane after the shutdown.  Actions for the spectro pipeline:

  * DONE: remove the preproc, exposures, and tiles/cumulative/TILEID files for exposures of these tiles
    * DONE: removed from daily
    * DONE: removed from everest
  * TODO: flag the exposures as bad in both everest and daily so that they won't be reprocessed in fuji and won't accidentally re-appear in daily
```
TILEID  PASS    RA      DEC    PROGRAM DONEFRAC
  1767     0  230.397   43.062    DARK   0.0000
  1825     0  329.126    1.365    DARK   0.5470
  2704     1  222.897    4.905    DARK   0.5241
  2786     1  240.394    9.573    DARK   0.2839
  2976     1  250.036    6.945    DARK   0.0000
 20218     0  235.919   16.769  BRIGHT   0.0000
 20250     0  244.768   22.561  BRIGHT   0.0000
 20307     0  346.874   30.797  BRIGHT   0.3315
 20802     0   31.789   31.667  BRIGHT   0.0000
 20833     0  313.737    0.650  BRIGHT   0.0000
 20852     0  318.470   11.652  BRIGHT   0.0000
 20855     0  332.470    0.917  BRIGHT   0.0145
 21116     0  200.430    8.841  BRIGHT   0.0000
 21273     0  344.455    2.172  BRIGHT   0.7377
 21283     0  356.352   30.536  BRIGHT   0.4028
```

**Comment by akremin** [comment]
As self documentation and because there were enough tiles to warrant development, I wrote a small bash script to identify nights/exposures corresponding to each of these tiles in the exposure tables and then run `desi_edit_exposure_table` to set their `LASTSTEP` to "`ignore`" (thus meaning they won't be processed).

The script and the list of tiles (copied from above) can be found here: `/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/custom/retire_tiles`

I ran this for the exposure tables in `everest` and `daily` (done by changing your environment variable `SPECPROD` to point to the proper prod). Everest will be synced back to the master versions for future releases, so these will never again be processed.
