### ISSUE TITLE
tilepix.fits assigns PETAL_LOC to boolean

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1373]
This was brought to my attention by @araichoor:

The new "`tilepix.fits`" file provided with `everest` uses one-bit for `PETAL_LOC`, so all values are 0 or 1 and are read in as a boolean instead of the petal location (0-9). I used astropy.table.Table.read(), astropy.io.fits.open(), and fitsio.read() and all provide the same result.

The json version of the file looks correct, in that petals of all numbers 0-9 are represented.

**Comment by sbailey** [comment]
Ugh!  That's my fault (though I haven't tracked down why yet).

Normally I wouldn't change a release post-facto, but the tilepix.fits file as-is is uselessly wrong, so I'm open to either completely removing it or replacing it with a corrected version.  Opinions+reasons welcome.  Thanks for already adding a caveat about that on the wiki page.

**Comment by sbailey** [comment]
For the record, this is due to https://github.com/astropy/astropy/issues/11963 where astropy silently converts signed 8-bit integers into booleans because the FITS standard doesn't support signed 8-bit integers (only unsigned; see [FITS standard 4.0](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) section 5.2.1).

The workaround is to use unsigned np.uint8 or signed 16-bit integers np.int16, but not np.int8.  I'll include that in a future PR updating several aspects of tilepix.

**Comment by moustakas** [comment]
Fixed in #1614.
