### ISSUE TITLE
tile_qa N(z) plots broken?

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1393]
Dumping into a ticket for later followup:
```
desi_tile_qa --prod /global/cfs/cdirs/desi/spectro/redux/everest -t 120 --outdir .
```
writes a QA file, but it is missing the N(z) histograms:
![image](https://user-images.githubusercontent.com/218471/131578609-6fc3b989-f127-4eab-964c-41bc5cdbc8ef.png)

In the log output:
```
INFO:tile_qa.py:69:compute_tile_qa: running missing exposure qa
WARNING:exposure_qa.py:54:compute_exposure_qa: no /global/cfs/cdirs/desi/spectro/redux/everest/preproc/20210407/00083530/fibermap-00083530.fits
WARNING:tile_qa.py:75:compute_tile_qa: failed to compute exposure qa
INFO:tile_qa.py:78:compute_tile_qa: reading /global/cfs/cdirs/desi/spectro/redux/everest/exposures/20210407/00083871/exposure-qa-00083871.fits
INFO:tile_qa.py:108:compute_tile_qa: reading /global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/120/20210407/coadd-0-120-thru20210407.fits
INFO:tile_qa.py:113:compute_tile_qa: reading /global/cfs/cdirs/desi/spectro/redux/everest/tiles/cumulative/120/20210407/redrock-0-120-thru20210407.fits
...
```
fibermap-00083530.fits is genuinely missing because that exposure was flagged as bad, so that could be improved, but doesn't seem directly related to the missing N(z).

**Comment by araichoor** [comment]
from a quick check at the code, it looks like it is because the n(z) is plotted for the main survey only:
https://github.com/desihub/desispec/blob/7d000c34e630d907abb5ab2fc83c429f4ea9084b/py/desispec/tile_qa_plot.py#L814-L815

The n(z) is based on a reference file, which comes from the main: https://github.com/desihub/desispec/blob/master/py/desispec/data/qa/qa-reference-nz.ecsv

I do not remember to what extent this choice has been discussed..

**Comment by sbailey** [comment]
@araichoor thanks for checking.  Indeed for SV I don't think it is worth making reference N(z) plots.  I'll close this ticket.
