### ISSUE TITLE
Comparison of everest redshift catalog files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1419]
# Executive Summary

* There are *expected* changes from SV1 to SV2 to SV3 to main.  *However*:
* `zpix-sv1-dark.fits` differs significantly from all other `zpix-*.fits` files.
* `ztile-sv1-bright-*.fits` differs significantly from `ztile-sv1-dark-*.fits`,
  which in turn differs significantly from all other `ztile-sv1-*.fits` files.
* `ztile-sv1-(bright|dark)-*.fits` files also differ significantly
  from all other `ztile-*.fits` files.
* More research is needed to resolve all of the anomalies in `ztile-sv1-(bright|dark)-*.fits` files.

# zpix

## main

These files are effectively identical in structure:

* `zpix-main-bright.fits`
* `zpix-main-dark.fits`

## sv1

These files are effectively identical in structure:

* `zpix-sv1-backup.fits`
* `zpix-sv1-bright.fits`
* `zpix-sv1-other.fits`

`zpix-sv1-backup.fits` has additional columns compared to `zpix-main-bright.fits`:

* `SV1_DESI_TARGET`
* `SV1_BGS_TARGET`
* `SV1_MWS_TARGET`
* `SV1_SCND_TARGET`

And the `SCND_TARGET` column is missing.

`zpix-sv1-dark.fits` has additional columns compared to `zpix-sv1-backup.fits`:

* `NUMTARGET`
* `BLOBDIST`
* `FIBERFLUX_IVAR_G`
* `FIBERFLUX_IVAR_R`
* `FIBERFLUX_IVAR_Z`
* `HPXPIXEL`

In addition the `RELEASE` column has a different data type (`J` versus `I` in
other files).

## sv2

These files are effectively identical in structure:

* `zpix-sv2-backup.fits`
* `zpix-sv2-bright.fits`
* `zpix-sv2-dark.fits`

`zpix-sv2-backup.fits` has additional columns compared to `zpix-main-bright.fits`:

* `SV2_DESI_TARGET`
* `SV2_BGS_TARGET`
* `SV2_MWS_TARGET`
* `SV2_SCND_TARGET`

And the `SCND_TARGET` column is missing.

## sv3

These files are effectively identical in structure:

* `zpix-sv3-backup.fits`
* `zpix-sv3-bright.fits`
* `zpix-sv3-dark.fits`

`zpix-sv3-backup.fits` has additional columns compared to `zpix-main-bright.fits`:

* `SV3_DESI_TARGET`
* `SV3_BGS_TARGET`
* `SV3_MWS_TARGET`
* `SV3_SCND_TARGET`

And the `SCND_TARGET` column is missing.

# ztile

In general every `ztile-*-cumulative.fits` file is effectively identical to the corresponding `ztile-*-pernight.fits` file.

## main

All of these files are effectively identical in structure:

* `ztile-main-bright-cumulative.fits`
* `ztile-main-bright-pernight.fits`
* `ztile-main-dark-cumulative.fits`
* `ztile-main-dark-pernight.fits`

## sv1

These files are effectively identical in structure:

* `ztile-sv1-backup-cumulative.fits`
* `ztile-sv1-backup-pernight.fits`
* `ztile-sv1-other-cumulative.fits`
* `ztile-sv1-other-pernight.fits`

`ztile-sv1-backup-cumulative.fits` has additional columns compared to `ztile-main-bright-cumulative.fits`:

* `SV1_DESI_TARGET`
* `SV1_BGS_TARGET`
* `SV1_MWS_TARGET`
* `SV1_SCND_TARGET`

And the `SCND_TARGET` column is missing.

These files are effectively identical in structure:

* `ztile-sv1-bright-cumulative.fits`
* `ztile-sv1-bright-pernight.fits`

However these files differ significantly from `ztile-sv1-backup-cumulative.fits` and `ztile-main-bright-cumulative.fits`.

These files are effectively identical in structure:

* `ztile-sv1-dark-cumulative.fits` 
* `ztile-sv1-dark-pernight.fits`

However these files differ significantly from `ztile-sv1-bright-cumulative.fits`, `ztile-sv1-backup-cumulative.fits` and `ztile-main-bright-cumulative.fits`.

## sv2

All these files are effectively identical in structure:

* `ztile-sv2-backup-cumulative.fits`
* `ztile-sv2-backup-pernight.fits`
* `ztile-sv2-bright-cumulative.fits`
* `ztile-sv2-bright-pernight.fits`
* `ztile-sv2-dark-cumulative.fits`
* `ztile-sv2-dark-pernight.fits`

`ztile-sv2-backup-cumulative.fits` has additional columns compared to `ztile-main-bright-cumulative.fits`:

* `SV2_DESI_TARGET`
* `SV2_BGS_TARGET`
* `SV2_MWS_TARGET`
* `SV2_SCND_TARGET`

And the `SCND_TARGET` column is missing.

## sv3

All these files are effectively identical in structure:

* `ztile-sv3-backup-cumulative.fits`
* `ztile-sv3-backup-pernight.fits`
* `ztile-sv3-bright-cumulative.fits`
* `ztile-sv3-bright-pernight.fits`
* `ztile-sv3-dark-cumulative.fits`
* `ztile-sv3-dark-pernight.fits`

`ztile-sv3-backup-cumulative.fits` has additional columns compared to `ztile-main-bright-cumulative.fits`:

* `SV3_DESI_TARGET`
* `SV3_BGS_TARGET`
* `SV3_MWS_TARGET`
* `SV3_SCND_TARGET`

**Comment by weaverba137** [comment]
Recalling that `ztile-sv1-backup-cumulative.fits` has only the expected differences relative to `ztile-main-bright-cumulative.fits`, `ztile-sv1-bright-cumulative.fits` has these columns displaced in ordering relative to `ztile-sv1-backup-cumulative.fits`.

* `MASKBITS`
* `FLUX_IVAR_W1`
* `FLUX_IVAR_W2`
* `SV1_SCND_TARGET`

Also, let me emphasize that this is in the `ZCATALOG` HDU, so this isn't necessarily due to differences in fibermap files.

**Comment by weaverba137** [comment]
`ztile-sv1-dark-cumulative.fits` similar column ordering displacement to `ztile-sv1-bright-cumulative.fits`.  *In addition*, it has the extra columns noted in `zpix-sv1-dark.fits`:

* `NUMTARGET`
* `BLOBDIST`
* `FIBERFLUX_IVAR_G`
* `FIBERFLUX_IVAR_R`
* `FIBERFLUX_IVAR_Z`
* `HPXPIXEL`

In addition the `RELEASE` column has a different data type (`J` versus `I` in other files).

The differences in ordering combined with the bright/dark difference account for all the anomalies among the `ztile-sv1-*.fits` files.

**Comment by sbailey** [comment]
The specific `desi_zcatalog` commands that generated each of these files for everest are listed in `/global/homes/d/desi/labeled_proc_run_files/everest/zcatalog/NOTES-zcatalog.txt`

This basically boils down to merging the REDSHIFTS+FIBERMAP HDUs from N>>1 individual redrock files, and then stacking them.  i.e. the ZCATALOG HDU is a merge of the bare-bones REDSHIFTS HDU and the FIBERMAP HDU (which descended from the input FIBERASSIGN HDU + info added by observations and processing steps).  The format discrepancies would arise from the input fibermaps in $DESI_ROOT/spectro/redux/everest/preproc/NIGHT/EXPID/fibermap*.fits having different formats, due to the input fiberassign files having differing formats.

Those original fibermap files come from `assemble_fibermap -n NIGHT -e EXPID -o OUTFILE` .

@weaverba137 can you trace backwards to identify SV1 fibermaps with different formats, and then update `assemble_fibermap` using those as example until they have the same format?  Since NUMTARGET, BLOBDIST, FIBERFLUX*, and HPXPIXEL were purposefully dropped from the fiberassign files, I think we can drop them during assemble_fibermap if they exist in the input files.  Similarly I'm hoping a type conversion of RELEASE will be possible, as well as any column reordering standarization.

**Comment by weaverba137** [comment]
@sbailey, sounds good, thank you for the pointer.

**Comment by sbailey** [comment]
@weaverba137 thanks.  While you're at it, the `assemble_fibermap` step is also the source of these mis-placed keywords which could be cleaned up while you are testing the consistency and validity of the generated fibermap files:
```
preproc fibermap **** Verification found 7 warning(s) and 5 error(s). ****
*** Error:   Keyword #202, SIMPLE is not allowed in extensions.
*** Error:   Keyword #554, EXTEND is not allowed in extensions.
*** Error:   Keyword #204, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #203, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #202, SIMPLE is duplicated or out of order.
```
(from desihub/desidatamodel#87)

**Comment by weaverba137** [comment]
Wow, so `desispec.io.util.addkeys()` has a [standard list of keywords to skip](https://github.com/desihub/desispec/blob/00c4ddc2980288571f184899f5b1aea149a2e733/py/desispec/io/util.py#L670).  Astonishingly, `SIMPLE`, etc. are not in that list.  @sbailey, it appears that you wrote `addkeys()`.  What was the logic in *not* skipping `SIMPLE` automatically?

**Comment by weaverba137** [comment]
Also, it's not clear that `addkeys()` preserves FITS comments.  How do you ensure that comments are copied?

**Comment by weaverba137** [comment]
Note to self: `addkeys()` should use https://docs.astropy.org/en/stable/io/fits/api/headers.html#astropy.io.fits.Header.extend.

**Comment by sbailey** [comment]
Q: Wow, so desispec.io.util.addkeys() has a standard list of keywords to skip. Astonishingly, SIMPLE, etc. are not in that list. @sbailey, it appears that you wrote addkeys(). What was the logic in not skipping SIMPLE automatically?

A: "Never attribute to malice that which is adequately explained by stupidity." (Hanlon's razor, variously attributed)

i.e. I just missed it, probably because when I first wrote it the case I had didn't need to strip SIMPLE, e.g. HDU 0 -> HDU 0, or HDU 1 bintable without SIMPLE -> HDU 1 bintable.  Feel free to strip SIMPLE and other keywords that should not be propagated that I may have missed.

Q: Also, it's not clear that addkeys() preserves FITS comments. How do you ensure that comments are copied?

A: I don't; they are also in the strip list, partially due to the next note about supporting dict-like objects.  Also, in some cases comments are meaningful to propagate and in other cases they aren't, and in the specific case of propagating raw data headers I don't think we have any COMMENT fields that should be propagated.

> Note to self: addkeys() should use https://docs.astropy.org/en/stable/io/fits/api/headers.html#astropy.io.fits.Header.extend.

`addkeys` purposefully takes dict-like inputs and outputs so that it works the same with `astropy.io.fits.Header`, `fitsio.FITSHDR`, plain `dict`, and `OrderedDict` (e.g. as used by `astropy.table.Table.meta`).  That limits some potential uses (e.g. you can't do COMMENT keys that appear multiple times if the output is a plain dict), but it provides flexibility, and even if it doesn't support propagating COMMENT I like that it works the same in all cases (including what is logged).

**Comment by weaverba137** [comment]
Sorry, let me be clear here: my concern is for comments on other types of Header Cards:
```
EQUINOX =   2000.0     / This comment!
```
not `COMMENT` or `HISTORY` cards.

**Comment by weaverba137** [comment]
So here's an interesting gotcha: ultimately, these troublesome keywords come from the `SPEC` HDU in the raw data file.  That HDU is *compressed*, which means it contains `ZSIMPLE` not `SIMPLE`, etc.  `fits.getheader()` helpfully "decompresses" the HDU cards, even though it is, in theory, not decompressing the data.  So, are any of the `Z*` header cards of interest downstream?  It would be very simple to eliminate those.

**Comment by sbailey** [comment]
> Sorry, let me be clear here: my concern is for comments on other types of Header Cards:
```
EQUINOX =   2000.0     / This comment!
```
> not COMMENT or HISTORY cards.

Thanks for clarifying; I had indeed misunderstood that.  Those comments are indeed dropped in the current implementation, and it would be preferable to propagate them, which would likely require some `if isinstance(...)` logic to handle the different cases.

Specific example:
When we read a fits table with `astropy.table.Table.read()`, the header keywords end up in the Table.meta OrderedDict.  Do the comments get lost, or are those encoded in the Table object somehow?

However, In the big picture, propagating these comments would be nice but other Fuji priorities like updating the datamodel and reviving the database are higher priority.

> So here's an interesting gotcha: ultimately, these troublesome keywords come from the SPEC HDU in the raw data file. That HDU is compressed, which means it contains ZSIMPLE not SIMPLE, etc. fits.getheader() helpfully "decompresses" the HDU cards, even though it is, in theory, not decompressing the data. So, are any of the Z* header cards of interest downstream? It would be very simple to eliminate those.

I suspect they are not needed downstream.  We're mainly trying to propage the "user" keywords like ADC settings, telescope pointing, shutter info, ...  i.e. I think you could strip anything that is causing a problem.  Not that "ZD" is used for the telescope zenith distance, so don't just strip all keywords that start with Z...

**Comment by weaverba137** [comment]
I'm currently dissecting `desispec.io.fibermap.assemble_fibermap()` in a notebook, and determining the exact nature of the `.meta` attribute is part of that.  In the bigger picture, I'm trying to figure out if we can propagate and merge the various raw headers separately, *as* FITS header objects, then write the header separately from the table data.  Alternatively, don't involve `astropy.table.Table` at all, but work directly with the FITS HDU objects.

Thank you for the warning about `ZD`.

**Comment by weaverba137** [comment]
Now that we are successfully loading all redshift catalogs into a single table (depending on file type: `zpix` and `ztile`), I think the purpose of this issue is satisfied.
