### ISSUE TITLE
Update calibration handling in desi_run_night

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1439]
Update calibration handling in desi_run_night, so that it:
1) Processes them before science exposures
2) Appropriately selects a complete set of cals to base the nightly psfs and fiberflats on
3) Optionally only processes one set of cals

**Comment by sbailey** [comment]
FWIW, I checked this on night 20211121 with a double set of arcs+flats:
```
desi_run_night --dry-run-level 2 --proc-obstypes dark,arc,flat,science -n 20211121
```
It submitted the first set of arcs + flats, including psfnight and fiberflatnight, then proceeded to submit the other arcs and flats before proceeding with science exposures.  

I then tried flagging the first set of cals as LASTSTEP=ignore, removing the processing table and re-running (dry-run) and it correctly picked up the second set of calibs.

i.e. in the first case it wasted some CPU time by processing arcs and flats that it didn't end up using, but it didn't fundamentally break things because the extra arcs/flats don't interfere with the basic bookkeeping of the psfnight, fiberflatnight, and science exposures depending upon those.  However, under the assumption that nights with extra cals are because there was something wrong with the cals, we should go through cases like this and pick which set we really want to keep and flag the rest.

These are the nights that I've found with a non-default number of arcs+flats that aren't already flagged as LASTSTEP=ignore:
```
NIGHT NUMARC NUMFLAT
20201215 20 12
20210112 40 12
20210119 20 14
20210131 20 24
20210205 17 12
20210215 20 24
20210222 15 12
20210303 0 16
20210320 20 24
20210403 15 12
20210411 20 24
20210616 10 28
20210624 10 28
20210917 20 24
20211120 20 24
20211121 20 24
20211122 20 24
20211128 20 12
```

**Comment by sbailey** [comment]
At the data telecon @julienguy volunteered to help select which cals should be used on these nights (thanks!).  In practice this will turn into calls like this:
```
desi_edit_exposure_table -n NIGHT -e FIRSTEXPID-LASTEXPID \
    -c LASTSTEP -v ignore --include-comment "dome lights were on"
```

so it is most useful to have the range of exposures to *discard* instead of the range of exposures to *keep*.

Note: in the above, NIGHT, FIRSTEXPID, and LASTEXPID are numbers to be filled in, but "LASTSTEP" really is just the string "LASTSTEP", i.e. the column name that is going to be updated to the value "ignore".

**Comment by akremin** [comment]
Thank you for the comments, Stephen. Your first message matches my expectations+experiences.

(1) on the list was accomplished in PR #1465 and, as Stephen stated, (3) is just a wish-list item as it doesn't cost anything except CPU time.

For (2), another set of eyes checking the nights Stephen listed would be useful. My recollection is as follows:

20201215 is the only night I remember explicitly where special effort needs to be made. On that night the first set of cals was bad, then the second was misconfigured and got 27 arcs+flats, then the third had the flats interrupted. So procedure is to run the second set of arcs+flats for a012345689, and the third set of arcs for a7.

I believe for the rest of the nights we can just take the first complete set.

**Comment by akremin** [comment]
And to elaborate on Stephen's second message: just providing a list of expids to exclude would be useful. 

I don't think we should run the commands for the master tables, as there is nothing inherently wrong with the data and post-Fuji we should improve the code to optionally skip over superfluous cals rather than flagging good data as bad. What I imagine is that the Fuji+Guadalupe "checkouts" of the tables will get these flagged prior to job submissions.

**Comment by akremin** [comment]
On slack @julienguy provided the following table:

```
Unnecessary or bad exposures to discard for Fuji
--------------------------------------------------
NIGHT,FIRST,LAST		comments
20201215,67895,67912		ignore first set of calibrations which was taken at wrong pointing, but second misses SP7
20201215,68105,68132		also ignore set of calibrations (despite SP7), because it has contamination by lines.
20210112,71973,72050		no science exposure that night so no need to process any calib
20210119,73012,73081		no science exposure that night so no need to process any calib
20210131,73978,74010 		ignore second series
20210205,74714,74721		ignore first series with Xe lamp issue
20210215,76065,76098		ignore second series
20210222,77588,77599		ignore second series because no flat (even though first series polluted a bit by light in the dome)
20210303,79169,79184		gain sequence, not a flat. no science data that night
20210320,81215,81248 		ignore second series
20210403,83294,83305		ignore second series
20210411,84368,84401		ignore second series
20210616,94887,94902 		gain sequence, not a flat.
20210624,95831,95885		no science exposure that night so no need to process any calib
20210917,100593,100626		ignore first series
20211120,109674,109707		ignore second series
20211121,109860,109893		ignore second series
20211122,110210,110243		ignore second series
20211128,111164,111197 		ignore first series with front illuminator on
20211128,111349,111360 		ignore third series
```

**Comment by akremin** [comment]
@julienguy   I have a few followup questions on your table of cals to skip. I had asked on Slack a while ago but didn't hear back:

> 20201215,68105,68132		also ignore set of calibrations (despite SP7), because it has contamination by lines.

You include the arcs in this third sequence. Did you find contamination in the arcs? It was previously known that they turned on the lights and ruined the flats, but the arcs were used for sp7 in Everest.

> 20210222,77588,77599		ignore second series because no flat (even though first series polluted a bit by light in the dome)

You’re advocating for using cals with dome light contamination for both arcs+flats,   and ignoring this second set of clean arcs?

**Comment by akremin** [comment]
Brief discussion with Julien and the decision is to go with the original guidance. For 20201215 it actually simplifies the processing such that we only need to deal with one set of arcs+flats. The downside is that we have to use default psfs+flats for SP7. For 20210222 we think the contamination is minor and the arcs+flats should be robust to it.

We can always back out these decisions if those nights show issues in early Fuji processing

**Comment by akremin** [comment]
I implemented the list as-is, though I did not perform any action on nights with no science exposures (we don't run them anyway) or on "ignore second set" comments (we will process the individual exposures but won't use them for cals anyway). The two choices were driven by the fact that the data were good but superfluous, so it felt wrong to flag them as bad. We will process a few extra exposures this way, and in the future we can algorithmically skip those types of exposures or indicate them with an additional column (e.g. `CALIBRATOR` column set to `False`)
