### ISSUE TITLE
EXPID 101421 not included in reduction of TILEID 22427

### ISSUE THREAD

**Issue by schlafly** [desihub/desispec#1504]
TILEID 22427 is the tile where petal 3 contains an extremely bright star, and which was considered good in the original reduction but bad in the rereduction.
old: https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/archive/22427/20210928/tile-qa-22427-thru20210923.png
new: https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/22427/20210923/tile-qa-22427-thru20210923.png
The old reduction has a lot of issues on petal 3 because of the very bright star, but is otherwise fine.  The new reduction includes EXPID 101420 but not 101421, so is very shallow everywhere, and has been marked bad.

The exposures-daily.csv file lists both 101420 and 101421 as good exposures with EFFTIMEs of 120 s.  @akremin 's inspection of the daily exposure tables shows that both exposures should be processed, and both exposures include cframes.  So it's unclear why the new reduction includes one EXPID but not the other.

**Comment by akremin** [comment]
I traced this to the EXP 101421 cframes being missing when the spectra files were generated. There are notes in the log files that this is the case, and the file timestamps corroborate it.

`kremin@cori21 [daily]$ ls -lt ./exposures/20210923/00101421/cframe*`
```
-rw-r----- 1 desi desi 86860800 Nov 16 17:19 ./exposures/20210923/00101421/cframe-z2-00101421.fits
-rw-r----- 1 desi desi 86860800 Nov 16 17:19 ./exposures/20210923/00101421/cframe-z5-00101421.fits
-rw-r----- 1 desi desi 86860800 Nov 16 17:19 ./exposures/20210923/00101421/cframe-z6-00101421.fits
-rw-r----- 1 desi desi 86860800 Nov 16 17:19 ./exposures/20210923/00101421/cframe-z4-00101421.fits
-rw-r----- 1 desi desi 86860800 Nov 16 17:19 ./exposures/20210923/00101421/cframe-z7-00101421.fits
...
```

`kremin@cori21 [daily]$ ls -lt ./tiles/cumulative/22427/20210923/spectra*`
```
-rw-r----- 1 desi desi 207705600 Nov 12 05:05 ./tiles/cumulative/22427/20210923/spectra-9-22427-thru20210923.fits
-rw-r----- 1 desi desi 207708480 Nov 12 05:05 ./tiles/cumulative/22427/20210923/spectra-5-22427-thru20210923.fits
-rw-r----- 1 desi desi 207711360 Nov 12 05:05 ./tiles/cumulative/22427/20210923/spectra-7-22427-thru20210923.fits
-rw-r----- 1 desi desi 207705600 Nov 12 05:05 ./tiles/cumulative/22427/20210923/spectra-6-22427-thru20210923.fits
...
```

What is still unclear is why the redshifts were run if the redshifts didn't exist. It was likely a human error in resubmitting failed redshift scripts, since nominally the pipeline submits these with job dependencies that require the cframe processing to complete successfully before executing the redshifting.

**Comment by schlafly** [comment]
Great.  To clean this up, we'll need to:
- get another processing of the tile
- update tiles-specstatus to be 'none' for this tile
- VI the tile
- rearchive the tile
- add to MTLs through MTL reprocessing update method.

**Comment by akremin** [comment]
This is now complete except for the MTL reprocessing update, which should happen tomorrow along with the rest of the reprocessing updates.

#### Actions performed

1. Removed old reprocessing (first archived version retained, but this reprocessing was never used for anything and was flagged as bad so wasn't archived. Therefore we could therefore be safely deleted).
2. Reprocessed the redshifts again to pick up `cframes` from both exposures.
3. Verified that the update didn't impact `tiles-daily.csv `or `exposures-daily.csv`, which it didn't since the `cframes` were there for both exposures when those tables were updated.
4. Checked out a copy of tiles-specstatus.ecsv and reset `QASTATUS` and `USER` to "none". This wasn't strictly necessary, but I did it so the `--new` flag to `desi_tile_vi` would pick up the tile.
5. VI'ed the tile and approved it.
6. Checked the update in to svn.
7. Updated the surveyops svn at NERSC.
8. Ran `desi_archive_tilenight -n 20210923 -t 22427` to archive the tile.

**Comment by akremin** [comment]
Note for the future: the link in the original post for the "new" processing now points to the fixed tile-qa image. This is a by-product of removing the old directory and writing in its place. Other than this ticket, that data was of no other use. Below are screenshots of the two tile qa's Eddie referred to in the original post and the final fixed version:

#### old
![image](https://user-images.githubusercontent.com/8572603/144944785-03f0f465-0dc7-4e93-ad31-f1c7767dc31b.png)old:

#### new
![image](https://user-images.githubusercontent.com/8572603/144944697-0c602675-bac6-457b-8292-fba8e5a7ddcf.png)

#### after fix
![image](https://user-images.githubusercontent.com/8572603/144944883-feddda30-a205-4eda-ae96-c3823270b11e.png)

**Comment by akremin** [comment]
MTL reprocessing occurred earlier in the week and this was included:
```
[kremin@dtn01 mtl]$ grep 22427 mtl-done-tiles.ecsv 
22427 2021-09-28T22:02:17+00:00 1.3.0 BRIGHT 20210923 20210928
22427 2021-12-14T18:47:49+00:00 2.3.0 BRIGHT 20210923 20211206
```

That was the last step, so closing this issue.
