### ISSUE TITLE
exptab edits overwritten when daily pipeline is running

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1510]
It appears that `desi_daily_proc_manager` keeps an exposure table in memory, and when it finds a new exposure it adds a row and then writes the table to exposure_tables/YEARMM/exposure_table_YEARMMDD.csv .  A side effect of this is that you can't flag exposures as bad while the daily pipeline is running since the next exposure will just overwrite your edits with what was in memory.

I think it would be better for the update to always re-read from disk, append the row, then re-write to disk, thus minimizing the time that an unlucky external update would get lost.  Does the pipeline track any other state in memory that would get lost if it always re-read the exposure table from disk before appending a new row?

In the meantime, I think the procedure for flagging exposures/amps/etc as bad is:
* either wait for the pipeline to finish and flag things as bad the next morning; or
* stop the pipeline, make the updates, and then restart

I'm pretty sure that @akremin has verbally mentioned this issue to me, but I'm not sure if it is in a ticket.  If this is a duplicate please reference the correct ticket and close this one.

**Comment by akremin** [comment]
What use case did you experience or are you imagining here? The only possible use I could see is that exposure tables are loaded to find what exposures should be coadded and redshifts in cumulative redshifts. So if a pipeline operator was very on top of things they could identify an issue in the exposure and flag it so that the cumulative redshift script doesn't use it. 

Other use cases I can think up are much better suited toward stopping the pipeline or waiting until morning, then cleaning things up properly

**Comment by sbailey** [comment]
Two cases, both related to cals not science exposures:
1. one of the days that I was running the pipeline had some hiccups on the afternoon cals that I wanted to flag as bad while it was fresh in my mind.  I marked them as bad without realizing that the entries were going to be overridden.  The next day I had to look up again what had happened and which exposures should be flagged as bad and re-flag them.
    * In particular I was flagging z3 as bad in the ZEROs so that it wouldn't be used in the future (e.g. in combination with DARKs taken later in the cloudy night), but the nightly pipeline only uses b0-b9 from the ZEROs so I thought didn't need to stop and restart the pipeline.
2. I think Anand may use the exposure tables in semi-realtime to know what data to look for for night QA etc.  I had flagged a dark exposure as bad so that he wouldn't use it for the night QA dark plot, but then the entry got overwritten and his code didn't know that it was bad.  Or something like that.

**Comment by akremin** [comment]
For the first case I can see why it'd be convenient to add the information into the table while it's fresh-in-mind even though the pipeline doesn't presently use z information for zeros. In all cases other than zeros, however, those bad cameras would impact processing such that things would need to be halted and cleaned up.

The second case is more inline with what I was thinking of. In such cases would you not need to stop the pipeline, cancel all jobs, remove the dark, resubmit, etc? Otherwise if you used the dark in processing then why wouldn't you use it for the QA meant to vet the data you used in the processing? It may be that the QA is for something other than the `badcolumn` processing, so again I see why edits would be useful. Please see my reasoning below for why I hesitate on this.

When the tables are loaded, all of the variables defining the state of the processing need to be reset to reflect the tables otherwise it could lead to inconsistencies and even contradictions. In scenario (2) above, the ignored dark would then cause the script to look for a new dark. If the old dark still existed, the job would execute successfully but not overwrite the data files on disk that weren't removed, which will lead to ambiguities and/or improper inputs being used for the later science processing that could easily be overlooked when glancing at thing the following morning.  One could imagine loading the exposure table but not changing the internal state variables, but I don't like the idea of carrying around a table with different information than what the variables say about the same data.

I'm also concerned that this would leave users with a false comfort that they've done something by flagging it in the exposure tables -- which isn't the case. Those jobs will have already been submitted and the data either already written or will be written when the jobs execute. I prefer to operate on the idea that the data/job/dependency cleanup occur at the same time that things are documented in the exposure tables.
