### ISSUE TITLE
desi_proc_dashboard failed vs. not yet run

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1550]
The desi_proc_dashboard seems to group genuine failures with jobs that simply haven't yet run, making it difficult to assess what really has failed until all of the jobs have cleared out of the queue.  e.g. for f4, it currently lists 20210202 has having "FAILED 17/17" when there are still 5 arcs + 12 flats that are in the queue and just haven't run.

Could someone other than Anthony help fix this?  The tables in $CFS/desi/spectro/redux/f4/processing_tables.csv have the info for what exposures are being processed by which queue jobs, which can be compared to squeue output to compare with pending jobs (likely needing an extra desi_proc_dashboard option to let a regular user check on desi-user production jobs for debugging, even if final usage will be run as desi user).

Example to run:
```
desi_proc_dashboard --specprod f4 --output-dir $CFS/desi/users/$USER/dashboard
```
and compare https://data.desi.lbl.gov/desi/users/USERNAME/dashboard/dashboard.html with what is pending in the queue from `squeue -u desi -o "%.18i %.9P %.25j %.8u %.2t %.10M %.6D %R"`

**Comment by akremin** [comment]
I agree that that this would be useful.

Since we already load the processing table in the dashboard to determine if something is "processing", we can use the existing infrastructure to "refresh" the job statuses using `desispec.workflow.queue.update_from_queue()`.

usage:
`ptable = update_from_queue(ptable)` 

This queries on Slurm jobid's and therefore doesn't need to designate a user or account to get the relevant information.

Additional thoughts:
The dashboard currently has a dropdown menu for "all", "processing", "unprocessed", and "unaccounted". I think the implementation we'd want is to add a fourth category "processed". This makes it slightly annoying because you'd have to look at "all" to see both "processed" and "processing", which will also bring in "unprocessed" exposures (e.g. long exptime arcs, etc.), but I think that is the price we will have to pay.

Then the top level accounting would be:
"Complete", "Failed", "Incomplete" would only do accounting on "processed" and we'd add a new value for "Processing" in the dropdown bar accounting.
