### ISSUE TITLE
calibration issues in F3

### ISSUE THREAD

**Issue by changhoonhahn** [desihub/desispec#1593]
I noticed a few recurring calibration issues in the pre-Fuji (F3) data reductions that aren't in Everest. I was comparing the spectra of BGS galaxies that have different redrock redshifts in Everest versus F3 for the pernight coadds. 

Below are a few examples: 
TILEID: 18
NIGHT: 20210430
PETAL: 3
TARGETID: 39627847622461162
<img width="606" alt="Screen Shot 2022-01-14 at 7 13 22 AM" src="https://user-images.githubusercontent.com/1895640/149513801-0175f894-c91e-456d-9985-404f52133766.png">

TILEID: 371
NIGHT: 20210430
PETAL: 3
TARGETID: 39633145326210122
<img width="612" alt="Screen Shot 2022-01-14 at 7 17 38 AM" src="https://user-images.githubusercontent.com/1895640/149514305-22ff5363-bebc-408a-9bc6-ee1f47511037.png">

TILEID: 589
NIGHT: 20210506
PETAL: 3
TARGETID: 39633145208767388
<img width="621" alt="Screen Shot 2022-01-14 at 7 20 01 AM" src="https://user-images.githubusercontent.com/1895640/149514626-a2113489-d4c6-4795-b626-fc18459a28f2.png">

It's always the 180th object in Petal 3.

**Comment by sbailey** [comment]
Thanks for the detailed report with examples; I've flagged this for Fuji.

**Comment by julienguy** [comment]
Still present with master version.
The sky is not subtracted at all for fiber 1680 of b3. 
It must have something to do with the handling of the fiber masks.

**Comment by julienguy** [comment]
It is caused by a bad/corrupted sky pcacorr template for this fiber and camera.
The sky model is totally wrong for this fiber, and (unexpectedly) this results in a throughput correction that is ~ 0. Removing the option ' --pca-corr ..../skycorr-pca-sm6-b3.fits' cures the problem, but the real fix is to inspect and correct the skycorr templates. I am going to have a look at this.

**Comment by sbailey** [comment]
Thanks for tracking down that surprising bug.  Perhaps stating the obvious: please check the skycorr-pca files for every other camera/fiber for any repeats of whatever caused this (or more subtle versions of it).

Moving from Fuji "to do" to "must do"

**Comment by julienguy** [comment]
Fiber 1680 in b3 is the only camera/fiber with a skycorr PCA component that is off. I am working on the code to make the PCA more robust.

**Comment by julienguy** [comment]
This issue is solved with the correction in PR #1598 to the PCA sky corr template of camera b3.
`plot_frame -i $DESI_SPECTRO_REDUX/jguy/exposures/20210430/00086730/sframe-?3-00086730.fits --fiber 1680 --legend`

![Screenshot from 2022-01-18 12-36-20](https://user-images.githubusercontent.com/5192160/150014845-d7175f62-b85d-40a9-b47e-906603d92351.png)
