### ISSUE TITLE
Fuji: missing qso* files (as of 15 Feb, 3pm Pacific)

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#1688]
@sbailey @akremin : if useful, I ve written a small script to check the outputs of a prod.
it just counts the number of existing files for all expected perexp/, pernight/, cumulative/ reductions, based on the exposures*fits file.
I attach the script, and the output .ecsv files for both prods.

I m checking the following files:
'SPECTRA', 'COADD', 'REDROCK', 'RRDETAILS', 'TILEQAFITS', 'TILEQAPNG', 'ZMTL', 'QSOQN', 'QSOMGII', 'EMLINEFIT'
then it s easy to check that the number of files matches the one of the existing SPECTRA.

I cannot find how to attach the files, I send them through slack.

doing that I notice the following reductions are missing some qso* files:
```
>>> d = Table.read("tmp-outputs-fuji.ecsv")
>>> sel = (d["QSOQN"] != d["SPECTRA"]) | (d["QSOMGII"] != d["SPECTRA"])
>>> d[sel]["FOLDER", "SPECTRA", "QSOQN", "QSOMGII"]
<Table length=18>
                                FOLDER                                SPECTRA QSOQN QSOMGII
                                str73                                  int64  int64  int64 
--------------------------------------------------------------------- ------- ----- -------
    /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/1/00083716      10     9       9
   /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/77/00084350      10     9       9
  /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/136/00083725      10     9       9
  /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/221/00084517      10     9       9
  /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/223/00085204      10     9       9
  /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/412/00084535      10     9       9
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80659/00079080       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80694/00072706       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80694/00079571       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80698/00079877       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80699/00074464       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80708/00077430      10     9       9
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80709/00079574       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80711/00085509      10     9       9
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80858/00079885       9     7       7
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80899/00081533       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/80902/00081101       9     8       8
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/81064/00082505       9     8       8
```

**Comment by sbailey** [comment]
Some exposures are missing a camera, e.g. tile 1 night 20210406 expid 83716 z7 which had a light leak saturation event (see the [nightwatch image](https://nightwatch.desi.lbl.gov/20210406/00083716/preproc-z7-00083716-4x.html) if you are curious).  The pernight and cumulative redshifts use z7 data from other exposures, but the perexp grouping doesn't have this data, resulting in a coadd files with only B and R, but not Z.

This causes the QSO afterburners to crash, e.g.
```
$> cd /global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/1/00083716
$> desi_qso_qn_afterburner --coadd coadd-7-1-exp00083716.fits --redrock redrock-7-1-exp00083716.fits   --output $SCRATCH/qso_qn.fits --target_selection all --save_target all

DEBUG: Read templates from /global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock-templates/0.7.2
INFO:desi_qso_qn_afterburner:385:<module>: SANITY CHECK: The indices of REDROCK HDU and FIBERMAP HDU match.
INFO:desi_qso_qn_afterburner:420:<module>: Nbr objetcs for QN: 500
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/fitsio/fitslib.py", line 1413, in __getitem__
    hdu = self.hdu_list[ext]
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_qso_qn_afterburner", line 421, in <module>
    QSO_from_QN = selection_targets_with_QN(redrock, fibermap, sel_to_QN,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_qso_qn_afterburner", line 217, in selection_targets_with_QN
    data, index_with_QN = load_desi_coadd(spectra_name, sel_to_QN)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/QuasarNP/0.1.2/lib/python3.9/site-packages/quasarnp/io.py", line 459, in load_desi_coadd
    flux = h[fluxname].read()[rows, :]
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/fitsio/fitslib.py", line 1431, in __getitem__
    raise IOError("extension not found: %s %s" % (ext, mess))
OSError: extension not found: z_flux (case insensitive)

```

@echaussidon can you start with the fuji branch, make a branch off of that, update the QSO afterburners to be robust to a missing camera, and then open a PR back to the fuji branch?  (if any of that git manipulation doesn't make sense, please make updates to any version of the qso after burners and we can sort out the branching and PRs).

You might want to fit the QSO anyway what whatever bands you have, or you might want to just treat it like the 'notargets' case and leave a file behind indicating that it ran and there was a problem, but we shouldn't completely crash on this case.

It might be tempting to say that the input spectra/coadd should be padded with zeros for Z instead of completely missing Z, but part of the original purpose of the spectra format was to be a generic collection of spectra from a generic set of bands, and downstream code should just use whatever bands it finds instead of hardcoding the B, R, and Z must exist.

**Comment by echaussidon** [comment]
Hi @sbailey, 

I could correct the problem for mgII afterburner but not directly for qn afterburner. The three bands are hard coded in quasarnp package: https://github.com/desihub/QuasarNP/blob/e37dcde3dc5bbfd69a67e21d2c42c42704fbf33d/quasarnp/io.py#L435

Since, having mgII without qn is useless (we cannot build the full quasar selection). I will create 'blank file' as for 'notargets' case.

I will make a PR soon to treat this problem.
