### ISSUE TITLE
Non-finite TARGET_RA,TARGET_DEC for some fuji early tiles

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#1711]
Tiles designed with _some_ fiberassign version < 2.4.0 have some non-finite TARGET_RA,TARGET_DEC (mostly for stuck fibers).
This affects fuji only.

That issue was apparently solved in fiberassign with PR https://github.com/desihub/fiberassign/pull/340, which has been used for tags >=2.4.0.
Working from the fuji `ztiles-SURVEY-PROGRAM-cumulative.fits` catalogs, I find that 432 tiles are affected, with 8 to 20 fibers per tile; the list is here: [tmp.txt](https://github.com/desihub/desispec/files/8121478/tmp.txt)

I also notice this "feature" appears with the TARGET_RA, TARGET_DEC columns having a `mask` properties:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/ztile-sv1-backup-cumulative.fits")
>>> "mask" in dir(d["TARGET_RA"])
True
>>> d["TARGET_RA"].mask.sum()
228
```
Catalogs with no such targets will not have the `mask` property:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/ztile-cmx-other-cumulative.fits")
>>> "mask" in dir(d["TARGET_RA"])
False
```

A "natural" consequence is that those TARGETIDs will not appear in the healpix reductions, as no healpix pixel can be associated to them.

**Comment by araichoor** [comment]
Just emphasizing the astropy 5.0 vs. previous versions difference, as I feel that can break some sanity checks made with previous versions.

With a previous astropy version (desi environment 21.7e)
```
>>> import astropy; astropy.__version__
'4.0.1.post1'
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/ztile-sv1-backup-cumulative.fits", "ZCATALOG")
>>> np.isnan(d["TARGET_RA"]).sum()
228
>>> "mask" in dir(d["TARGET_RA"])
False
```

Wtih astropy version 5.0 (current desi master environment):
```
>>> import astropy; astropy.__version__
'5.0'
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/fuji/zcatalog/ztile-sv1-backup-cumulative.fits", "ZCATALOG")
>>> np.isnan(d["TARGET_RA"]).sum()
0
>>> d["TARGET_RA"].mask.sum()
228
```

**Comment by sbailey** [comment]
For the record: we had decided not to fix these in fiberassign svn because that would change what ICS/platemaker would have done with these tiles.  Options:
* intercept these during assemble_fibermap, and replace the NaN with the FIBER_RA, FIBER_DEC values from platemaker.
* fix them in svn, with the argument that the raw data contain the reference file that was actually used for the record, and ICS/platemaker/focalplane have changed so much in the meantime that even the original fiberassign file wouldn't generate a reproducible observation anyway.

astropy 5 Table masking NaN: ugh, yeah, this has bitten us multiple times.  Our current recommendation is to use `Table(fitsio.read(filename))` if you just need the data portion but still want to get it into an astropy Table for convenience (column manipulation, joining, pretty printing...), or `desispec.io.read_table(filename)` if you also want it to propagate header keywords.  Both of those retain NaN as NaN, and blank strings as blanks strings without masking.

**Comment by sbailey** [comment]
I think there is no more action to take for Fuji, so I'm removing this from the Fuji dashboard but will leave open until we decide if we want to handle this at the assemble_fibermap level or try to patch the svn files or otherwise live with it (I'm currently leaning towards assemble_fibermap fix).
