### ISSUE TITLE
How to best add new QA functions/scripts to be run on daily reductions?

### ISSUE THREAD

**Issue by forero** [desihub/desispec#1728]
In particular, what would be the best way to add permutation entropy QA functions/scripts?

Here https://github.com/forero/desientropy/tree/main/py/desientropy I have clean versions of all the functions I need to handle files and compute the permutation entropy on: a) the redshifts as a function of fiber index and b) the sky sframe  data.

However, I am not sure what would be the preferred way to fold them in into the current daily QA infrastructure.

**Comment by akremin** [comment]
I think the most obvious place for this would be to include function calls in the nightqa script (https://github.com/desihub/desispec/blob/master/bin/desi_night_qa) that was developed by @araichoor so that these plots are generated and displayed in the nightly qa page. The python functions would then be placed somewhere under `desispec/py/desispec/` so that they are importable.

If you want to add an executable script for broader use and convenience, you are welcome to put that in `desispec/bin/`, but place the main body of the code in `desispec/py/desispec/scripts/ `so that we can also call it from within the nightqa framework.

If you don't think we need an executable script then you have more freedom on where you put the new python code. You could consider either placing it in `desispec/py/desispec/tile_qa.py` or adding your own `desi_entropy_qa.py` file to `desispec/py/desispec/`.

A broader to-do for us is to better organize files within the package, but that is beyond the scope of this.

**Comment by forero** [comment]
Thanks @akremin !

**Comment by akremin** [comment]
Not a problem!

FYI: I pointed to the wrong qa python file, I meant to point to `night_qa.py`. The above should say `desispec/py/desispec/night_qa.py`. 

Anand should be able to provide more advice on integration.

**Comment by araichoor** [comment]
Sorry for not being responsive...
Thanks a lot @forero for pushing that!

The "natural" way I would see that would be to add it to `desispec/py/desispec/night_qa.py`, as @akremin says.
That script generates the various informations in e.g., https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220309/, and creates the `nightqa-NIGHT.html` file which wraps all of those.
That is run with the 10am pacific daily cron job, once all per-tile files should be there.

I don t know if it s better to make a separate, identified script, with all the related functions, and call them in night_qa.py; or to just add those functions inside night_qa.py.
The former would have those functions more visible (if someone wants to use them for something else), but the data team may want to limit the number of scripts..

Anyway, the second step would be to decide how to present the results: @forero could you provide few examples?
i.e. I don t know if the output is some plot, or some table, or just some list of tiles/petals, etc.
Once we have this we just need to add another tab/section in the `nightqa-NIGHT.html` page.

**Comment by forero** [comment]
Thanks for your advice, @akremin and @araichoor. I will add all the code into night_qa.py. I will produce plots and figures similar to tile-qa-*.png but focused on the permutation entropy for the redshift distribution and the sky_sframes. Those plots could be then presented as a another tab/section in the `nightqa-NIGHT.html` page.
I will now close this issue and open the corresponding PR once it is ready.
