### ISSUE TITLE
Possible typo in resubmission attempts in daily processing

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1769]
@sbailey in looking through `procfuncs.py` for unrelated reasons the following line jumped out to me as problematic. Should it be:
`log.error(f'{jobname} err.output={err.output}')` , or is this some sort of python elegance that I am unfamiliar with?

https://github.com/desihub/desispec/blob/69a38749e36ec173714b6e08405f42b91ebe29d2/py/desispec/workflow/procfuncs.py#L464

**Comment by sbailey** [comment]
I think it's a "python elegance".  With formatted strings, `f'{blat=}'` is shorthand for `f'blat={blat}'` (syntax introduced in [python 3.8](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging)).  Thus `log.error(f'{jobname} {err.output=}')` is equivalent to `log.error(f'{jobname} err.output={err.output}')`.

If I answered the question that you asked, feel free to double check that and then close issue, or otherwise re-explain the concern.

**Comment by akremin** [comment]
Apologies for the noise. I tested it on my personal machine but I now see it is running an outdated 3.7 installation, which throws an error at that syntax. I'll close the issue.
