### ISSUE TITLE
Write CCD chi2 image to further mask cosmics

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#181]
After accounting for masked CCD pixel from the cosmic finder (DC3e run), there are still significant cosmic ray spikes in the extracted spectra (a few per spectrum).  We can certainly reduce this a lot by using a CCD chi2 image. specter tools can be used for this without much difficulty. This can be an additional pipeline step after the extractions (this would be more flexible than modifying the extraction script, allowing alternative extraction implementations).

**Comment by sbailey** [comment]
Two challenges with implementing it after the extractions:

1. We would need to deconvolve the spectrum by the resolution matrix in order to get to a (ringy) pre-convolution version of the spectrum before projecting it onto the CCD
2. Calculating the PSF at every wavelength for every fiber is a non-trivial amount of computation time

We might still want to provide such a tool, but we should directly include writing the model image as an extraction option and use an internally calculated chi2 image for masking spectral bins.
