### ISSUE TITLE
Official name of redshift database

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#1832]
What do we officially call the redshift database being developed in `desispec.database.redshift`? This could have some effect on, *e.g.* selecting a DNS name for easy access to a future Spin service. This issue was split out from #1819.

**Comment by weaverba137** [comment]
@sbailey, it might be nice to decide on this before next Friday.

**Comment by sbailey** [comment]
I'm not sure about a URL name, but for docs let's refer to this as a "spectroscopic production database", i.e. it is a database that represents the results of a spectroscopic production run.  We had previously avoided that name because in an earlier version of the pipeline we had a database that was tracking the production jobs but we no longer use that.

**Comment by weaverba137** [comment]
I've updated the core database code with this new terminology in #1928.
