### ISSUE TITLE
Why do we need both air and vacuum wavelengths for arc line data?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#186]
The data/arc_lines directory currently contains a number of .ascii files that seem to be redundant.  Why do we need *e.g.* both ArI_air.ascii & ArI_vacuum.ascii?  Aren't the existing `airtovac()` and `vactoair()` functions good enough?

**Comment by sbailey** [comment]
Assigning to @profxj; the definitive answer may come from either him or @julienguy .

**Comment by profxj** [comment]
For backwards compatibility, i.e. in case the vacuum approach failed
for some unforeseen reason.

I think we can remove them after we have something working well
on the test stand data.

> On May 12, 2016, at 5:03 PM, sbailey <notifications@github.com> wrote:
> 
> Assigning to @profxj <https://github.com/profxj>; the definitive answer may come from either him or @julienguy <https://github.com/julienguy> .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/desihub/desispec/issues/186#issuecomment-218919516>
> !DSPAM:826,573519ca255952455014670!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by djschlegel** [comment]
I'd suggest any line lists use vacuum below 2000 Ang and air above 2000 Ang, since that's how NIST measures and provides the wavelengths.  It looks like the python conversion routines, like the IDL ones, expect a mixed version of vacuum+air also.

Note that we found a bug in the IDL version of the conversion routines, and I think python might have inherited both the incorrect formula and the mis-approximation to that formula.  Attaching the SDSS fix for this in case you want to check the python code:

Carlos Prieto pointed out that the air-to-vacuum
wavelength conversion is based upon the Morton (1991 Ap.J. Suppl.
77, 119) formula that appears to be incorrect at the level of
approx 0.2 km/s.  Furthermore, this implementation approximated
that formula with only two terms of a Taylor expansion.
Replace this with the Ciddor (1996) formula which has been
adopted by the International Association of Geodesy, and
appears to be more widely used, see, e.g.
  http://emtoolbox.nist.gov/Wavelength/Documentation.asp
  http://refractiveindex.info/?group=GASES&material=Air
(Ticket #1247).

**Comment by julienguy** [comment]
* NIST also provides wavelength in vacuum so we can still rely on this without having to do a conversion ourselves. 

* Today, everything in DESI has wavelength in vacuum which was not the case 2 weeks ago.
We had the code in air, and the templates in vacuum, which was pretty bad.

* Because it's only a convention, I do not see how one or the other can pose any problem.

* I suggest we stick to what we have now, wavelength in vacuum.

* If decided otherwise we have to modify again desisim, desisim-testdata, desispec, specex, desimodel,  and all the templates we have on disk at NERSC.

**Comment by weaverba137** [comment]
OK, it looks like I started three different conversations, but I think the conclusion is that it is OK to remove the *air.ascii files.

**Comment by julienguy** [comment]
It's also OK to leave them in the code for now. 
If you remove them, you also have to remove all the code of bootcalib that deals with wavelength in air (which is an option).

**Comment by weaverba137** [comment]
To move forward, I'm going to leave in the air files for now, and we can revisit this once we are absolutely certain the all-vacuum code is working.
