### ISSUE TITLE
path of log incorrect in dashboard hyperlink

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#1903]
Path of log files appears to be missing the "run" before "scripts" in hyperlinks in the "LOG FILE" column in the dashboard, e.g., https://data.desi.lbl.gov/desi/spectro/redux/daily/dashboard/dashboard.html.

**Comment by akremin** [comment]
The referenced dashboard is actually a sym-link of this one under /run/ : https://data.desi.lbl.gov/desi/spectro/redux/daily/run/dashboard/dashboard.html

My guess is that the relative links are failing because they’re relative to the /run/ version, and that is also why I haven't run this issue.

The best solution seems to be to remove the sym-link and simply use the dashboard in it's new location. The move was made months ago to be more consistent with reprocessing directories. The old dashboard was replaced by a sym-link for those with browser bookmarks. I think that was reasonable, but if the links no longer work then this might be a case where we remove the page and let people reset their bookmarks to the new location.
