### ISSUE TITLE
Redundant header keywords in brick files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#191]
brick files repeat the header keywords 'BRICKNAM' and 'CHANNEL' in every HDU.  Isn't the first HDU sufficient?

**Comment by sbailey** [comment]
It can be convenient for each HDU to be semi-independent, even if it involves replicated keywords.  If we did want HDU0 to be the sole place for common keywords, we should use the [INHERIT = T convention](http://fits.gsfc.nasa.gov/registry/inherit.html) to indicate that HDU0 has keywords of interest, but from what I can tell astropy doesn't support that.  i.e. let's leave this as-is.

Note: Our raw data will use INHERIT = T so that each CCD doesn't replicate all the common telemetry, DATE-OBS, etc. keywords from HDU 0 of the raw data file.  `desispec.io.read_raw` will take care of merging the HDU0 and HDUn keywords in that case.
