### ISSUE TITLE
desi_zproc expects cframes for spectrographs with bad cameras flagged

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desispec#1923]
In scripts/proc_tilenight.py, cframe files are generated only if [none of the three cameras](https://github.com/desihub/desispec/blob/main/py/desispec/scripts/proc_tilenight.py#L106) are flagged as bad on the corresponding exposure-spectrograph combination.

In scripts/zroc.py, on the other hand, crames are expected if [any of the three cameras](https://github.com/desihub/desispec/blob/main/py/desispec/scripts/zproc.py#L325-L334) was not flagged as bad on the corresponding exposure-spectrograph combination.

This causes desi_zproc to fail unexpectedly when it does not find cframe files corresponding to exposure-spectrograph combinations with one or two cameras flagged as bad.

@sbailey please confirm whether the above description is accurate and, if so, determine the appropriate solution.

**Comment by sbailey** [comment]
For the purposes of Iron we are going to handle this by flagging entire petals as bad on nights when every exposure for a given (tile,camera) has been bad.  This has been the dailyops procedure from @akremin and for the purposes of redshift fitting it is equivalent since we can't flux calibrate the other cameras on that petal anyway.  I'm going to leave the ticket open since zproc could do better with this, but I'll remove it from the Iron project.

**Comment by akremin** [comment]
I confirmed yesterday that since Dec 11, 2020 there are no other instances of this occurring outside of this 20221119-20221120 window. As Stephen correctly summarized we have historically flagged the entire petal as bad if an individual camera is bad, because we cannot fit standard stars on that petal and therefore can't flux calibrate those remaining cameras or fit redshifts to the spectra.

Note there are instances when a camera was bad on one exposure but not on all exposures of a tile for a night. Those can still be properly fit, so we do not need to flag the entire petal in those instances.

We can discuss whether to reassess this approach in the future, but that is independent of `desi_zproc`.


I will flag petal 7 as bad for the following that were identified as having this issue. 
```	
Identified incomplete spectrographs:
	Night 20221119 Tile 42600: a069b7r7
	Night 20221119 Tile 43023: a069b7r7
	Night 20221119 Tile 83200: a069b7r7
	Night 20221119 Tile 83201: a069b7r7
	Night 20221119 Tile 83202: a069b7r7
	Night 20221119 Tile 83203: a069b7r7
	Night 20221119 Tile 83204: a069b7r7
	Night 20221119 Tile 83205: a069b7r7
	Night 20221119 Tile 83206: a069b7r7
	Night 20221119 Tile 83207: a069b7r7
	Night 20221119 Tile 83235: a069b7r7
	Night 20221120 Tile 42007: a069b7r7
	Night 20221120 Tile 42054: a069b7r7
	Night 20221120 Tile 42599: a069b7r7
	Night 20221120 Tile 43026: a069b7r7
	Night 20221120 Tile 43032: a069b7r7
	Night 20221120 Tile 43073: a069b7r7
	Night 20221120 Tile 83205: a069b7r7
	Night 20221120 Tile 83206: a069b7r7
	Night 20221120 Tile 83207: a069b7r7
	Night 20221120 Tile 83208: a069b7r7
	Night 20221120 Tile 83209: a069b7r7
	Night 20221120 Tile 83235: a069b7r7
	Night 20221120 Tile 83236: a069b7r7
```

**Comment by akremin** [comment]
For the record -- while tilenight may attempt to submit any cameras in this particular scenario, they will only run through sky subtraction and will fail in standard star fitting, as they did for the tiles here. So `desi_zproc` is correct in not expecting to find those cframes.

Here I show a few examples from that night that show the cframes are missing:
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/8572603/212444287-ca800f93-cffb-48f6-bbc3-1ec5f6ca5997.png">


I have flagged p7 as bad for 20221119 and 20221120. Nothing appears to need rerunning since that petal didn't have cframes or redshifts anyway. I'll leave the sframes, etc. for p7 as harmless and valid daily reductions.
