### ISSUE TITLE
Add columns for FIRST_NIGHT, LAST_NIGHT, and MJD information to Coadd files (FIBERMAP extension)

### ISSUE THREAD

**Issue by stephjuneau** [desihub/desispec#1930]
The FIBERMAP extension of the spectra coadd files replaces some exposure-specific columns with summary columns, e.g. NIGHT should become FIRST_NIGHT, LAST_NIGHT, and NUM_NIGHT as described [here](https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/healpix/SURVEY/PROGRAM/PIXGROUP/PIXNUM/coadd-SURVEY-PROGRAM-PIXNUM.html). Only NUM_NIGHT is present so FIRST_NIGHT and LAST_NIGHT need to be added.

Similarly, adding the MJD version of this information in the form of: MIN_MJD, MAX_MJD, MEAN_MJD would be the same approach and require getting the MJD from EXP_FIBERMAP to report the summary values in FIBERMAP.

This is needed for the Himalayas version of the COADD files (at least Healpix coadds) but having the fix available could be useful for some EDR VACs as well.

**Comment by andreufont** [comment]
@sbailey - is there a consensus about adding this column also in future releases? If this was the case, we would modify our Lya pipeline to use LAST_NIGHT to decide the blinding strategy. If not, we would look for alternative solutions (like figuring out the pipeline release / mountain)

**Comment by stephjuneau** [comment]
Hi @andreufont, my understanding is that @sbailey added this issue to the Himalayas project so that it should be implemented for the year 1 data and then propagate to the next specprod (Iron) and so on.

**Comment by andreufont** [comment]
Great. @julienguy and @theabbybault already added a preliminary version of this column to preliminary quasar catalogs, so that we can develop and test our blinding software. By the way, @julienguy mentioned that the "ztile catalogs" have a column named "LASTNIGHT, instead of "LAST_NIGHT". We should use consistent namings for these columns.

**Comment by julienguy** [comment]
I would like to mention that the information about all the NIGHT , EXPID , TILEID used for a healpix coadd is actually already saved in the extension "EXP_FIBERMAP" of the healpix files. So we can add summary information in the "FIBERMAP" extension for convenience, but there is no blocking factor to propagate information like LAST_NIGHT in higher level catalogs. Thank you @araichoor for noting that.

**Comment by andreufont** [comment]
It would be useful if the data team decided between LASTNIGHT and LAST_NIGHT. We have implemented the former in Picca, but it would be easy to change

**Comment by stephjuneau** [comment]
The advantage of LAST_NIGHT (and FIRST_NIGHT) is that it would be consistent with NUM_NIGHT which already exists in the FIBERMAP extension of the healpix files (I haven't checked the tile coadd files to see if they have NUMNIGHT or NUM_NIGHT). Andreu, Julien or Abby - could you point to the piece of code that you're using now to obtain the last night information? Stephen mentioned that it would be useful to include a pointer or example in this issue to help with the implementation and I haven't had any time to dig into the current code myself.

**Comment by ashleyjross** [comment]
A function to do so (copied from a script @julienguy wrote) has been added to the QSO catalog maker script: https://github.com/desihub/LSS/blob/main/scripts/main/mkQSO.py#L80

If that works, one could copy it into desispec for the healpix zcatalog creation (note that it requires the ztile zcatalog has already been produced).

**Comment by stephjuneau** [comment]
Thanks @ashleyjross! Looking at the function, I wonder if we could create a modified version that reads the info from the  EXP_FIBERMAP extension (or wherever that extension obtains the NIGHT information from). The motivation is to be robust to moving away from tile files and toward only healpix files. Also, is there a consensus to using LASTNIGHT instead of LAST_NIGHT? I prefer LAST_NIGHT because it's more consistent with NUM_NIGHT which already exists. Having both notations will end up being confusing very quickly. (Cc @moustakas @weaverba137 @sbailey @julienguy @andreufont @theabbybault)

**Comment by ashleyjross** [comment]
Lya switched to LASTNIGHT because the column is LASTNIGHT in the ztiles-*.fits zcatalogs.

**Comment by ashleyjross** [comment]
(I agree it is probably better to get the info from the fibermap and I'm very happy for anyone else to code that up as the solution.)

**Comment by stephjuneau** [comment]
Is it too late to switch to LAST_NIGHT everywhere? Otherwise we should use LASTNIGHT and adopt FIRSTNIGHT.

**Comment by sbailey** [comment]
Thoughts:
* We won't make any last minute changes to any *pre-existing* columns, since that could break analysis scripts and create inconsistencies for analyzing fuji / guadalupe vs. iron .
* Where we do have it in current spectro pipeline outputs, it is "LASTNIGHT", not "LAST_NIGHT".
* Although we could still *add* columns without breaking existing scripts, I'm inclined to not make a last minute addition since the information is derivable from EXP_FIBERMAP, which exists for coadd, redrock, and summary stack zcatalog/ztile and zpix files, **although not zcatalog/zall**.
* If we do make a change, I'd be more inclinded to propagate EXP_FIBERMAP into zall since that would provide *all* the per-exposure information, instead of selectively choosing in a rush which ones deserve first/last/mean/rms summaries and later regretting missing some other ones.
  * Counter argument 1: zall is already huge (23 GB), this would make it even bigger (28 GB?)
  * Counter argument 2: that may not address the original convenience request which I think was about knowing the first/last NIGHT or MJD included in a *healpix* coadd, not the zall file.
  * It's unclear to me if that convenience request was because they didn't know the information was available in the EXP_FIBERMAP HDU of the same files, or because it is too inefficient to derive the information for N>>1 targets on the fly from EXP_FIBERMAP, which I admit is a pain.  @stephjuneau ?

Documenting the situation and some history:
  * In denali and prior, coadds had a single coadded FIBERMAP with FIRST_NIGHT, LAST_NIGHT, NUM_NIGHT, but which lost per-exposure information like exactly which nights went into the coadd.
  * In everest and afterwards, FIBERMAP was split into FIBERMAP (coadd-level information) and EXP_FIBERMAP (exposure-level information).
    * FIRST_NIGHT and LAST_NIGHT were dropped from FIBERMAP since they could be derived from EXP_FIBERMAP, though NUM_NIGHT was renamed COADD_NUMNIGHT and kept.
    * The [datamodel prose descriptions](https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/tiles/GROUPTYPE/TILEID/GROUPID/coadd-SPECTROGRAPH-TILEID-GROUPID.html) still mention FIRST_NIGHT, LAST_NIGHT, NUM_NIGHT even though those columns have disappeared from the tables (in both the data and the datamodel).
  * As far as I can tell, we don't use "LAST_NIGHT" or "NUM_NIGHT" (with an underscore) anywhere in the spectro pipeline starting with everest (they did appear in denali).
  * When creating the zcatalog/ztile-*cumulative.fits stacked catalogs, a LASTNIGHT column is added, propagated from the "NIGHT" (meaning "last night" but fitting within 8 char) header keyword since that is needed to track an entry in the ztile-*cumulative.fits file back to the coadd/redrock/spectra files since that is used in the directory and filenames.

**Comment by sbailey** [comment]
FWIW, this is a code snippet to derive LASTNIGHT from EXP_FIBERMAP in the same TARGETID order as a redshift catalog.  I'm sure there is  a more efficient method to avoid the loop and intermediate dictionary, but I haven't found it yet (what I need is a version of `np.unique` that returns targets in the order found, not in sorted order).

```python
import fitsio
import numpy as np

# load redshift catalog, and per-exposure info that went into that catalog
zcat = fitsio.read('zpix-main-dark.fits', 'ZCATALOG')
expinfo = fitsio.read('zpix-main-dark.fits', 'EXP_FIBERMAP', columns=['TARGETID', 'NIGHT', 'MJD'])

# sort expinfo by NIGHT in descending order
expinfo = expinfo[np.argsort(-expinfo['NIGHT'])]

# identify first appearance for each TARGETID, which is now the largest NIGHT (i.e. LASTNIGHT)
lastnight_map = dict()
for targetid, i in zip(*np.unique(expinfo['TARGETID'], return_index=True)):
    lastnight_map[targetid] = expinfo['NIGHT'][i]

# convert into an array row-matched to zcat (i.e. it could be added as a column)
lastnight = np.array([lastnight_map[tid] for tid in zcat['TARGETID']])
```

If we don't add additional columns, at minimum we should provide utility functions or tutorials/cookbooks to help users do operations like this, since this isn't trivial.

**Comment by ashleyjross** [comment]
(I think you can avoid at least the explicit loop with astropy.table unique and join functions, but I'm guessing you're also trying to avoid using anything beyond numpy.) I think I agree it makes the most sense to copy this into the QSO catalog making and include something like this as an example in the ultimate documentation.

**Comment by araichoor** [comment]
a possibly another "pure-numpy" way to do that would be to use `np.lexsort()`, which is quite a handy function.
if I didn t mess up, here is a code snippet, which takes advantage that `zcat["TARGETID"]` is a unique list.
with `himalayas`, it s 2+ times faster.

```
# get the TARGETID sorting indices
ii = zcat["TARGETID"].argsort()

# sort expinfo first by increasing TARGETID, then by decreasing NIGHT
jj = np.lexsort((-expinfo["NIGHT"], expinfo["TARGETID"]))
expinfo = expinfo[jj]
# this way, the indexes returned by np.unique() should catch the latest night
_, jj = np.unique(expinfo["TARGETID"], return_index=True)
expinfo = expinfo[jj]

# sanity check
assert(np.all(zcat["TARGETID"][ii] == expinfo["TARGETID"]))

# get the lastnight
lastnight = np.zeros(len(zcat), dtype=int)
lastnight[ii] = expinfo["NIGHT"]
```

**Comment by moustakas** [comment]
I'm just trying to catch up on this ticket. It looks like the code has been contributed and it just needs to be inserted into the right function, but I'm a little unclear about where it belongs. I'd be happy to open a short PR but can someone direct me to which coadd-generating script is appropriate?

**Comment by stephjuneau** [comment]
Hi all, to answer some of @sbailey's questions about the goal/motivation, it was to have the info for each TARGETID per healpix so the "zall" catalog would also be a fine place to store this. In the case of the healpix coadd files, the fix could be in the documentation only for now. Maybe one solution could be to add the function when creating the "zall" file which is a step further down the workflow after all the individual zpix catalogs are created anyway? (avoids the risk of introducing a new bug in the zpix files).

**Comment by moustakas** [comment]
Thanks @stephjuneau. So it looks like there's no time-sensitive action item then.

**Comment by stephjuneau** [comment]
@moustakas right, assuming we can update how we combine the zpix-* files into the zall-* at a later time while iron is running. We could also discuss whether it's also needed in the coadd files but I could go without if it's in zall. Would this work, @sbailey ?

**Comment by sbailey** [comment]
We could do this as a second (or third) tag for Iron to make the final zcatalogs, but we need the PR ASAP since we will be done with the initial processing and ready to make the catalogs possibly as early as tomorrow depending upon how quickly Perlmutter comes back from its current degraded state.

The code to update is bin/desi_zcatalog which is used to create the zpix and ztile files (which then get read by desispec.zcatalog.create_summary_catalog to create the zall files combining data across dark/bright/backup/other).

**Comment by stephjuneau** [comment]
Summary of decisions made today at the Data telecon: we will add `FIRSTNIGHT, LASTNIGHT` as int(32) and also `MIN_MJD, MEAN_MJD, MAX_MJD` in float(64) to redshift value-added catalogs (zcat VAC) for EDR, and add them in desispec.coaddition.coadd_fibermap() for DR1+ (but not include `CENTER_MJD`). For information, Cc. @sbailey @weaverba137 @ashleyjross @andreufont @julienguy @theabbybault et al.
