### ISSUE TITLE
Dry run mode functionality for pipeline scripts

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#2038]
A recent change to query the Slurm scheduler prior to job submission will break the ability to run `desi_daily_proc_manager` and `desi_run_night` on a machine that doesn't have a Slurm scheduler.

The simple solution is to propagate `dry_run` to `queue_info_from_qids`, but then that would require updating the `dry_run` mode for that function to only return the requested set of columns, and with the requested Slurm jobid's. Currently, it returns a copied table from several years ago with outdated jobid's and the default set of columns.

This raises the large question of what we want `dry_run` to do.  It used to operate in the strict sense of not interacting with Slurm. But perhaps we do want it to get information from Slurm so that its mock actions are realistic to the current state of jobs, rather than being more self-contained but less realistic.

**Comment by sbailey** [comment]
Good catch.  I think we should keep dry-run as *not* interacting with slurm at all.  The simplest fix to restore dry-run functionality on a laptop would to be change [procfuncs.py L451](https://github.com/desihub/desispec/blob/main/py/desispec/workflow/procfuncs.py#L451) to include a dry run check before proceeding with filtering the dependencies:
```python
    if len(dep_qids) > 0 and dry_run==0:
        dep_table = queue_info_from_qids(np.asarray(dep_qids), columns='jobid,state')
        ...
```
That means dry-run doesn't exercise the full chain, but that seems ok compared to propagating `dry_run` into `queue_info_from_qids` just so that it can create a fake `dep_table` to return.
