### ISSUE TITLE
no module named fitsio

### ISSUE THREAD

**Issue by haixiangshu** [desihub/desispec#2083]
when import from desispec 
terminal tells ModuleNotFoundError: No module named 'fitsio'

**Comment by moustakas** [comment]
Hi @haixiangshu. `desispec` and other DESI packages have a number of dependencies like `fitsio` in order to work properly. Please take a look at the installation instructions here and feel free to reopen this ticket if you still have issues:
https://data.desi.lbl.gov/doc/releases/edr/software-version/#command-line-instructions-for-installing-desi-code

Also note that you can reach the DESI team with any questions you may have here:
https://help.desi.lbl.gov/

**Comment by haixiangshu** [comment]
Thank you for replying ,the problem has been solved.
