### ISSUE TITLE
duplicates in iron tilepix.fits

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#2108]
I notice that there are lots of repeats `$DESI_ROOT/spectro/redux/iron/healpix/tilepix.fits` file, which I think is a small bug.
apologies in advance if that s already identified (or if it s not a bug!)

I suspect that each exposure generates a set of row in `tilepix.fits`.
I was looking at TILEID=82636; e.g.:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/iron/healpix/tilepix.fits")
>>> d[(d["TILEID"] == 82636) & (d["PETAL_LOC"] == 0) & (d["HEALPIX"] == 27239)]
<Table length=8>
TILEID  SURVEY PROGRAM PETAL_LOC HEALPIX
int32   bytes7  bytes6   int16    int32 
------ ------- ------- --------- -------
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
 82636 special   other         0   27239
```
and I notice that TILEID=82636 has eight exposures in `exposures-iron.csv`.

another hint confirming that each expid generates a row: the number of repeats in `tilepix.fits` and the number of repeats of TILEID in `exposures-iron.csv` are similar:
```
>>> d = Table.read("/global/cfs/cdirs/desi/spectro/redux/iron/healpix/tilepix.fits")
>>> xs = np.array(["{}-{}-{}-{}-{}".format(t, s, p, pet, h) for t, s, p, pet, h in zip(d["TILEID"], d["SURVEY"], d["PROGRAM"], d["PETAL_LOC"], d["HEALPIX"])])
>>> unqxs, counts = np.unique(xs, return_counts=True)
>>> np.unique(counts)
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 30])
>>> e = Table.read("/global/cfs/cdirs/desi/spectro/redux/iron/exposures-iron.fits", "EXPOSURES")
>>> expids, counts = np.unique(e["TILEID"], return_counts=True)
>>> np.unique(counts)
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 30])
```
I don t see anything obvious looking at the code.
note that:
- `$DESI_ROOT/spectro/redux/fuji/healpix/tilepix.fits` is not affected by that, i.e. there are no repeats there;
- re-running `desi_assemble_tilepix` with the `desispec/0.56.5` version generates a `tilepix.fits` file with no repeat; so maybe this file was generate with some in-development code?

**Comment by sbailey** [comment]
Indeed, this is a bug.  To avoid having to re-read and re-parse all of the fibermap files, productions now generate a `preproc/NIGHT/EXPID/tilepix-TILEID.json` file as part of initial processing.  For iron, these were combined together using `/global/homes/d/desi/labeled_proc_run_files/iron/combine_tilepix.py` .  That attempted to avoid repeat entries, but made an int vs. str error in dictionary keys:
```python
tilepix = dict()
...
if tileid not in tilepix:  # should have been `str(tileid)`
    ...
    tilepix[str(tileid)] = data[str(tileid)]
    ...
```

The key needed to be a string for the purposes of dumping the dictionary to json, since json keys have to be strings not integers.

In the spirit of patching, I think it would be ok to post-facto update the iron tilepix.fits and tilepix.json files to not have duplicates.  Thoughts?

**Comment by araichoor** [comment]
thanks for the prompt explanation.
my 2 cents would be to patch, but I m not sure of the implications, so I ll let more relevant people answer here.
maybe @moustakas uses that file in fastspecfit?

**Comment by moustakas** [comment]
Thanks for tagging me, @araichoor. I don't use the `tilepix.fits` file in production; just for choosing random test pixels, so patching is fine with me. 

I _do_ use the `$DESI_ROOT/spectro/redux/{specprod}/tiles-{specprod}.ecsv` when fitting the cumulative coadds (in order to map tileid to survey), but, again, I don't fit those coadds in production.

**Comment by moustakas** [comment]
I've patched the `tilepix.fits` and `tilepix.json` files for Iron, per the discussion above.

The modified (debugged) merging code can be found here:
`/pscratch/sd/i/ioannis/patched-iron-tilepix/combine_tilepix.py`

With minimal differences:
```bash
diff combine_tilepix.py /global/homes/d/desi/labeled_proc_run_files/iron/combine_tilepix.py
13c13
< exp = Table.read(findfile('exposures', specprod='iron'), 'EXPOSURES')
---
> exp = Table.read(findfile('exposures'), 'EXPOSURES')
18,19c18,19
<     if str(tileid) not in tilepix:
<         tpfile = findfile('tilepix', night, expid, tile=tileid, specprod='iron')
---
>     if tileid not in tilepix:
>         tpfile = findfile('tilepix', night, expid, tile=tileid)
```

This tidbit (per @araichoor) confirms that all's well (i.e., no duplicates in the new file):
```
>>> d = Table.read('tilepix.fits')
>>> xs = np.array(["{}-{}-{}-{}-{}".format(t, s, p, pet, h) for t, s, p, pet, h in zip(d["TILEID"], d["SURVEY"], d["PROGRAM"], d["PETAL_LOC"], d["HEALPIX"])])
>>> unqxs, counts = np.unique(xs, return_counts=True)
>>> assert(len(d) == len(xs) == len(unqxs))
>>> set(counts)
  {1}
```

Finally, if @sbailey @akremin @weaverba137 agree that it's OK to patch, the requisite move is something like:
```
cp /pscratch/sd/i/ioannis/patched-iron-tilepix/tilepix.{fits,json} /global/cfs/cdirs/desi/public/dr1/spectro/redux/iron/healpix/
```
(Plus checksum, backup, etc.)

**Comment by sbailey** [comment]
Thanks to @weaverba137 for reminding me about this, and @moustakas and @araichoor for the fix + checks.  Looks good, let's proceed.

**Comment by weaverba137** [comment]
These files exist in multiple places, so a checklist:

- [ ] NERSC CFS
- [ ] NERSC HPSS
- [ ] Tucson
- [ ] Utah

**Comment by weaverba137** [comment]
@moustakas, somehow while attempting to copy the files, your version of `tilepix.json` got overwritten. Please recreate the files.

**Comment by moustakas** [comment]
@weaverba137 you should be able to run the "make the tilepix files" code (from any directory you'd like) by loading the DESI software stack (`main` is fine; no header cards are written to these files) and then (re)-running:
```
/pscratch/sd/i/ioannis/patched-iron-tilepix/combine_tilepix.py
```

**Comment by weaverba137** [comment]
Thanx @moustakas! I was able to run it, but I note for the record that I had to use `desimodules/main`, rather than, *e.g.* `desimodules/23.1`. I will put those in place momentarily.

Is the `combine_tilepix.py` code checked in anywhere, or will that never need to be run for future specprods, *i.e.* Jura?

Finally, for the record, I have kept a copy of the original tilepix files in HPSS, as well as backing up the new files.

**Comment by weaverba137** [comment]
All copies of these files have been updated. Close when ready.

**Comment by moustakas** [comment]
@sbailey should comment on if this script should be checked in somewhere. Closing.

**Comment by sbailey** [comment]
For the record: this custom script for iron is superseded by desispec/bin/desi_assemble_tilepix
