### ISSUE TITLE
check_env in the integration test does not check for SPECPROD

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#218]
The check_env() function in the integration test does not check for SPECPROD, even though that is now required.  It should also check that `$SPECPROD == $PRODNAME`.  That is, they should have the same value.

**Comment by sbailey** [comment]
The current state of needing both SPECPROD and PRODNAME is probably my fault and is a buggy situation.  We should fix this by requiring SPECPROD (see #127) and deprecating PRODNAME, rather than requiring both to be set.  I'll assign this to myself.

I will attempt to support both while issuing a deprecation warning for PRODNAME so that current configuration scripts will continue to work.  But if that turns out to be a pain, I will at minimum update it so that we don't require both.

**Comment by sbailey** [comment]
I directly pushed the simple commit a61c81329b14ab1c8f85ea2ba8a8c7237a2da4ff to master to go back to using just PRODNAME.  At NERSC, the problem was that desitree was setting both SPECPROD and PRODNAME, and the cronjob setup was overriding only one of them while the code was preferring the other.

I'm leaving the #127 PRODNAME -> SPECPROD migration for later.  I have it working on my laptop but will not open a PR until after the pipeline infrastructure stabilizes.
