### ISSUE TITLE
How can one determine which template files are needed?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#219]
During a recent integration test on my home system, the test crashed because I had templates/star_templates/v1.0, not templates/star_templates/v1.1.

This has been a recurring problem.  Unless one has expert knowledge, one must actually run the pipeline, find where it crashed, then figure out what files were missing.

So, where are the template versions recorded, & how can someone verify that they have the correct versions installed on their home system (without just downloading everything)?

**Comment by weaverba137** [comment]
PS, I've been running with these templates installed `basis_templates/`, `calib/` and `star_templates/`.  I don't know if others are required, *e.g.* `cosmics/`.

Also, I need to send another round of `fix_permissions.sh` requests, because not all the template directories are visible at http://portal.nersc.gov/project/desi/collab/spectro/templates/.

**Comment by tskisner** [comment]
Currently the lamplines for specex and the star templates are the two data files that cannot be determined by environment variables.  As such, they are written to the master config file for the pipeline (prod/run/options.yaml).  Although I find environment variables annoying, they do have the benefit of allowing data files to be portably found on any system.  If we could obtain these paths from the environment, then the remainder of the global features in options.yaml are portable.

**Comment by weaverba137** [comment]
In #207 @sbailey mentioned basis_templates/v2.2, but in most of the desisim module files I've looked at on NERSC, `$DESI_BASIS_TEMPLATES` is still set to  `<= v2.0`.  The only place I can see where it is v2.2. is the master module file on edison.  So hypothetically, if I were looking for which version to use, & only looked at cori, I'd think v2.0.

**Comment by sbailey** [comment]
1. I agree that the current situation is a problem
2. I welcome ideas for what would be easy and clean to do instead

Addeing @moustakas to the assignee list for this thoughts on how to manage where the templates are and what versions are required.

**Comment by moustakas** [comment]
The templates in ```$DESI_BASIS_TEMPLATES``` are really designed for simulations; they're far too bulky for the pipeline. I propose we select a smallish set of templates centered around F-star temperatures and put those in the data directory of desispec.  (```idlspec2d``` does this -- the Kurucz stellar models are in the etc directory and take up about 2MB.)  

There are ~40 (out of ~930) stellar models with Teff around ~6000 K, which would take up around 20MB. We can probably cull this down further by being more selective with metallicity and surface gravity, although without u-band we're going to inevitably select F-stars a broader range of metallicities.  (Gaia spectrophotometry may help with this.)

Another tidbit to keep in mind: we (the Targeting WG) are considering choosing a broader range of flux standards, including A stars and white dwarfs, so that's something to keep in mind if we move the standard-star templates into the desispec code base.

Thoughts?

**Comment by sbailey** [comment]
Further bits of information, but not disagreeing with anything John wrote:
* The integration test needs the full set of templates to generate a variety of target classes to simulate.  This is the only place that desispec depends upon desisim and the full set of templates.
* The current standard star selection uses the full set of stellar templates and then for each observed standard, it trims the templates down to those that match the input photometry (with some buffer to account for errors).  i.e. it matches photometry without making assumptions about Teff etc.

**Comment by weaverba137** [comment]
The documentation here addresses this problem: https://desi.lbl.gov/trac/wiki/Pipeline/Install#SetNecessaryEnvironmentVariablesandData
If this is insufficient, please open a new issue with specific concerns.

**Comment by timahutchinson** [comment]
I notice in that documentation, redmonster is still being cloned from the bitbucket repo.  As that's no longer being kept up-to-date, it should probably be changed to clone from either my or desispec's repo.

**Comment by weaverba137** [comment]
Good point, I will fix that.
