### ISSUE TITLE
Merge various integration test shell scripts

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#224]
In the process of working on pipeline install instructions, #170, I've created some shell scripts similar to cron_dailytest.sh.  I need to merge these into cron_dailytest.sh or some more general-purpose wrapper script.

**Comment by sbailey** [comment]
the purpose of `cron_dailytest.sh` is to
1. bootstrap the minimal cron environment using the already installed code
2. update the latest master copies of our code
3. run the integration test to ensure that the master version of all our products remains self consistent.

If your scripts are testing the installation procedure, let's bring that in as a separate script.  If they are expanding what the integration test does or other stuff on the existing installed code, then merging into cron_dailytest.sh could be good.

i.e. please itemize what the new scripts do and we can pick whether they should be merged into cron_dailytest.sh or come in as separate scripts/cronjobs.

I consider this an optional feature for the Pipeline 2016b milestone.  If it makes it in, great.  If not, we'll decouple this ticket from the milestone.

**Comment by weaverba137** [comment]
Here are the features not currently present in cron_dailytest.sh:

* Perform a "from scratch" install of pipeline on a bare account, *then* run the integration test.
* Perform installs with either desiInstall or Anaconda.
* Install tagged versions instead of master.

**Comment by sbailey** [comment]
These are all good things to have, but let's bring them in as separate scripts.  We might consider running them weekly or as-needed rather than nightly since I expect that we will break the installation methods less frequently than we might break inter-package communication.  And once we have verified that a given set of tags works together, we don't have to reverify that every night.

Super double bonus points if the "install tagged versions" can auto-recognize what the latest tagged versions are and use those rather than having to maintain that list by hand, but let's proceed with whatever you have.
