### ISSUE TITLE
Pb with Lyman-alpha detection around z~3.7 with redrock

### ISSUE THREAD

**Issue by echaussidon** [desihub/desispec#2278]
Hi, 

As already noticed in the previous spectro release, redrock detects fake Lyman-alpha emission peak around z\~3.8 i.e. for an emission peak located between two arms of the spectrograph. (Note that the effect should also exist around z\~5.2). 

Attached the redshift distribution of the QSO targets that are SPECTYPE=='QSO':
<img width="701" alt="Capture d’écran 2024-06-10 à 23 06 56" src="https://github.com/desihub/desispec/assets/47702632/b6a548c1-9c29-41cd-92ca-3ed5b4fd04a3">

**Comment by echaussidon** [comment]
@julienguy

**Comment by sbailey** [comment]
This has been discussed on the DESI internal Slack, but documenting here before closing:

The z~3.8 excess comes from sky fibers.  Since they are good fibers with valid sky spectra, they don't get a COADD_FIBERSTATUS bit set, but they can be identified with ZWARN bit 0 (SKY) set, or OBJTYPE=SKY.  Or even better, accept only ZWARN=0 or 4 and OBJTYPE=TGT (targets, i.e. not BAD, NON, SKY, or blank).

![image](https://github.com/user-attachments/assets/7fe1013b-dd14-4279-a3d7-3f7d990f905e)

![image](https://github.com/user-attachments/assets/08184628-acc9-4cd8-a038-1fd7d1410763)

Also note that there are sky-fiber QSO attractor solutions at z\~0.5 and z\~1.0 that are removed by making those cuts too:

![image](https://github.com/user-attachments/assets/5106b281-f310-446b-9a2d-f9a8117ca173)
