### ISSUE TITLE
20240730 - 20240805 tiles set to unsure because of r1

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#2316]
opening a ticket for the record (sorry I forgot to do that):
-  new cte on r1 has been identified on 20240730 data (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1722538227361809);
- while waiting for a fix, all tiles from 20240730, 20240801, 20240802, 20240803, and 20240805 have been set to "unsure";
- cte offsets added on Aug. 8: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1723122081176099, https://desi.lbl.gov/trac/changeset/1166/calib

20240730 - 20240805 nights have been reprocessed on Aug. 12.
I am going to re-QA those.

**Comment by araichoor** [comment]
I am re-QA’ing the 20240730-20240805 nights that have been re-processed with the new r1 cte fix.
I have just checked 20240730 so far.
it looks good, especially in terms of redshifts and lya (individual tiles plot, overall per-petal diagnoses).

though I notice a small feature in the sframesky, at the bluest pixel: see the white pattern at the very left (over the “1” in red):
<img width="1015" alt="sframesky-20240730-00246358" src="https://github.com/user-attachments/assets/3207617c-8c27-4e5b-ae4c-f316241f7cf5">


and I also see some excess of z~0.5 in the skyzfiber plot.
to make it more visible, I compile here all the redshifts of the sky fibers for maindark tiles with efftime > 850s since 20240730:
![tmp](https://github.com/user-attachments/assets/d831e9fa-f742-4433-999d-529bc11e4957)

I suspect that:
- the small feature in the sframesky at the very blue wavelengths are harmless;
- the excess at z~0.5 in the skyzfiber is ok (ie we cannot correctly correct the effect).
and that I can pass all tiles as "valid".

I ll just wait until tomorrow to allow anyone to chime in (@julienguy, @schlafly ?), in case this deserves more investigation.

**Comment by julienguy** [comment]
The "small feature in the sframesky at the very blue wavelengths" is caused by a negative sky model in that region.
I see the step in the sky flux as a function of fiber number from the CTE correction at the expected fiber ids from the defined OFFCOLSA: '450:1184,1184:2056' calibration param, but I am surprised that the amplitude of the steps is much larger at 5764A than at 6080A or 6880A.

Sky model flux as a function of fiber number for some wavelengths (from the file ```/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20240730/00246358/sky-r1-00246358.fits.gz```)

![Screenshot from 2024-08-12 16-17-30](https://github.com/user-attachments/assets/f54a2504-cba6-40c1-a07c-ef9e5ecaac63)

**Comment by julienguy** [comment]
The variation of the offset was caused by the flat field correction applied to the sky model, that also corrects for variations from spectrograph to spectrograph and can have large variations at the shortest or largest wavelength because of the dichroics. 

So the problem here simply a limitation of the OFFSET correction that is constant across wavelength: it fails when the sky level becomes lower than the correction to apply, which happens at the shortest wavelengths because of the dichroic.

**Comment by schlafly** [comment]
Thanks Anand.  I don't think we have good alternatives to this CTE correction at present, and if there aren't major impacts on the redshifts, let's move forward with it.  i.e., please mark as good, thank you!

**Comment by araichoor** [comment]
thanks both for the investigation + feedback.
I ll continue QA'ing those, and validate if nothing else shows up.

**Comment by araichoor** [comment]
ok, I ve QA-validated tiles from 20240730, 20240801, 20240802, 20240803, and 20240805 (https://desi.lbl.gov/trac/changeset/3985/data).
I ve moved all their status from “unsure” to “valid”.
there were 65 tiles (bright=16, dark=49).

**Comment by araichoor** [comment]
closing the ticket.
