### ISSUE TITLE
PSF failure r5 fibers 353,354 in k1 test

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2328]
The k1 test run had 17 failures like "ERROR:qa.py:37:trace_psf_qa: overlapping traces for fibers 353 and 354 in /global/cfs/cdirs/desi/spectro/redux/k1/exposures/20210704/00097319/fit-psf-r5-00097319_14.fits" on 7 nights spanning 20210109 through 20210704.  Some exposures in this time range worked, and later nights did not have this problem.  These also successfully ran in Jura.

Usually the cause of a new failure like this is an updated pixmask causing a fiber to have an unstable trace solution, and the fix is often to add the fiber to the BADCOLUMNFIBERS list.  Though see https://github.com/desihub/specex/issues/71 for examples where the trace is mostly ok, but a mask at the edge of the CCD causes overlapping traces and losing the entire fiber.

Investigate the what changed from Jura -> K1, what's going on with those fibers, and whether masking one/both of them is needed.

This is a blocking factor for Kibo.

**Comment by julienguy** [comment]
In pixmask-sm9-r-20201014.fits.gz, 2 columns where masked (X=2856,2857) because of electronic cross-talk from bright columns in other amplifiers. They intersect fibers 2852,2853 (similarity with CCD column number is a coincidence). I flagged both as BADCOLUMNFIBERS in sm9-r.yaml for the calibration configs with the same mask file, and did svn commit and update at NERSC. Please rerun.

**Comment by sbailey** [comment]
Thanks.  Fixed for k1 re-run.  Closing.
