### ISSUE TITLE
bug in tileqa dependency tracking

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2342]
There is a bug in the ztile job dependency tracking for the tileqa step, causing many ztile jobs in Kibo to exit early.  Example from kibo/tiles/cumulative/80616/20201223/logs/tile-qa-80616-thru20201223.log:
```
ERROR:util.py:90:runcmd: missing input /dvs_ro/cfs/cdirs/desi/spectro/redux/kibo/exposures/20201220/00068794/exposure-qa-00068794.fits
ERROR:util.py:90:runcmd: missing input /dvs_ro/cfs/cdirs/desi/spectro/redux/kibo/exposures/20201222/00068795/exposure-qa-00068795.fits
ERROR:util.py:90:runcmd: missing input /dvs_ro/cfs/cdirs/desi/spectro/redux/kibo/exposures/20201223/00068796/exposure-qa-00068796.fits
CRITICAL:util.py:101:runcmd: FAILED missing required inputs: desispec.scripts.tileqa.main(['-g', 'cumulative', '-n', '20201223', '-t', '80616'])
```

Those exposure IDs are from tile 80616, but are from night 20201219, not 20201220, 20201222, and 20201223.

For reference, this tileqa dependency checking was introduced in PR #2306, which included cross-night testing, and has been used for a month of daily operations with cross night tiles so it isn't immediately obvious what is wrong.  After fixing we'll need to cut a new tag and resubmit a bunch of ztile jobs.  In the meantime I'm letting Kibo proceed

Thanks for @dmargala for watching the kibo production closely and noticing the large number of ztile crashes.

**Comment by akremin** [comment]
There is a flawed assumption in that PR that nights and exposure ids are index-matched lists. It turns out that they are not, so when we  do:
```
        for expid, night in zip(expids, nights):
            infiles.append(findfile('exposureqa', expid=expid, night=night, readonly=True))
```
on lines 614 - 615 in zproc.py, this produces the erroneous filepaths.

There are two ways to tackle this:

1. Update the code to open the exposure tables for just the nights specified and create the desired lists.
2. Drop this input check since we now have cross-night redshift job dependencies and we should therefore never be running zproc if the files haven't been generated by the tilenight job.

(1) is the most complete but requires a little bit of coding. (2) is simplest. I think we want belt-and-suspenders here, so (1) is the best option, but if it turns into too much surgery then (2) might be the pragmatic choice at that point.
