### ISSUE TITLE
Do we need the extremely verbose python version string in headers?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#268]
When the Python version is injected into FITS headers, it results in a very long string:

```
DEPNAM00= 'python  '
DEPVER00= '3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) &'
CONTINUE  ' [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]'
```

When fitsverify sees this, it throws a warning:

```
*** Warning: The OGIP long string keyword convention is used without the
             recommended LONGSTRN keyword.  (HEASARC Convention)
```

It would be nice to suppress this warning so that it doesn't distract from more serious warnings & errors.

**Comment by weaverba137** [comment]
PS, because the dependencies seem to get injected into almost every extension,   this one warning can turn into 4 or more.  Do we actually need the dependency information in every extension?

**Comment by sbailey** [comment]
The python version comes via `desiutil.depend.add_dependencies` which gets the python version from `sys.version` (while replacing '\n' with ' ' so that it will work for FITS).  If you know of a less verbose way to get an informative version, we could update that.  Although it is quite verbose, each individual piece of information is potentially useful, especially at NERSC where one might trip across multiple versions of python compiled against multiple different compilers.  We could drop back to just grabbing the initial x.y.z version number and leave it to a log message to print the full python version if that is really really needed.

It would be fine if just the first HDU with data had the dependencies, though the fibermap is propagated from earlier files and could have dependencies come along for the ride unless we explicitly strip them.
