### ISSUE TITLE
write a fast and simple coadder

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#276]
We need a fast and simple spectrum coadder, even if it isn't optimal.  `desispec.coaddition` provides a mathematically optimal coadder but it is so CPU and memory intensive that we haven't been using it.  Redmonster needs a log-lambda binned coadd as a starting point and we're currently using `desispec.interpolation.resample_flux` for that purpose, but it isn't really a valid coadder for the reason documented in closed issue #272 .

The simplest useful version could assume that overlapping bins are aligned (e.g. x1=[1,2,3]; x2=[2,3,4]) and coadd to the superset of input wavelengths.  Weighting / error propagation should be included.  A more complete version would also
- allow specifying the output sampling grid and/or bin edges
- allow non-aligned overlapping bins (e.g. x1=[1,2,3]; x2 = [2.1, 3.1, 4.1])
- include some propagation of resolution matrix information

**Comment by dkirkby** [comment]
I should be able to take a first pass at this next week, to atone for writing the impractical spectroperfect coadder.

**Comment by sbailey** [comment]
Thanks for the offer, but I'd rather have you focus on the simulation realism and desihub/specsim#43, since they more directly need your expertise.  We'll want this fast coadder eventually but it is a relatively low priority for now and multiple other people could also do this.  But if knocking this off would make for a relaxing evening to clear your mind from the other tasks, ok.

**Comment by dkirkby** [comment]
Related to this, the bottleneck in the already-implemented spectroperfect coadds is solving the eigensystem of a large sparse matrix.  The new [spectra C++ library](https://github.com/yixuan/spectra/) looks promising here and should be evaluated.

**Comment by tskisner** [comment]
If we are going to port some internals of desispec to compiled code, that sounds great to me!  We should consider lots of things if we go that direction.  Historically there has been substantial bias from @sbailey against compiled code.  This was largely the reason I stopped work on the HARP codebase.  The central argument is that there are only a few developers in the collaboration that are truly comfortable with C++.  I think to overcome those arguments we would have to keep the compiled codebase to a very focused library of tools that have minimal external dependencies and strict style guidelines and unit tests.  On the other hand, I personally feel that we will eventually have to do this in order to get good performance on modern architectures.  If we do go down this route, I think that the C++ tools should be in a standalone library (distutils really sucks at building compiled code with arbitrary compiler options).  Then we can use ctypes or cython to call that library directly.

Anyway, this might be worth a larger discussion as part of the ultra-general WBS milestone, "finalize spectral extraction".

**Comment by dkirkby** [comment]
I agree with all of that.  We don't need (or perhaps want) a lot of C++ developers touching desispec code, but there are some well-defined numerical tasks that are not well supported in python (sparse matrix eigensolvers in this case).  This particular package is header only, which might simplify the distutils install.

**Comment by ngbusca** [comment]
@sbailey working towards the first simpler version with overlapping wavelength bins, is it the case that all bricks have a common grid? How are the extraction grids chosen?

**Comment by sbailey** [comment]
All bricks for a given spectroscopic pipeline run will have the same wavelength grid; it is determined by the parameters to the desi_extract_spectra script run early in the pipeline.  Different runs could have different grids, so you should derive the grid from the bricks themselves, but if you get the grid from one brick it should work for all other bricks within the same production.

For consideration: the redrock Target object has a lightweight ivar coadder that also propagates the effective resolution matrix for that coadd.  You could use that code or at least the math from that code.

https://github.com/desihub/redrock/blob/master/py/redrock/dataobj.py#L92-L137

**Comment by sbailey** [comment]
Coadder implemented in PR #805.  Closing.
