### ISSUE TITLE
Reduce python startup time

### ISSUE THREAD

**Issue by tskisner** [desihub/desispec#296]
This issue is to track progress reducing startup time at NERSC.  There are many opinions about this, but the order I will be exploring is:

1.  Pyinstaller.  Widely used, cross platform, and I have used it to successfully bundle complex apps that use anaconda, qt, matplotlib, mpi4py, and external compiled libraries.  Last I checked (some months ago) *astropy* was yet again the problem with this.  Only one script (desi_pipe_run) would need to be bundled, and I have already written a spec file for this.  I will revisit with latest pyinstaller version.

2.  NERSC-blessed container solution, a.k.a. shifter.  I will start with an Ubuntu LTS image.

3.  Homegrown local solution.

**Comment by rainwoodman** [comment]
On the homegrown side, Kaylan and I worked out a way to use hpcp-gnu with python-mpi-bcast at https://github.com/rainwoodman/python-mpi-bcast/tree/master/nersc-hpcp

**Comment by tskisner** [comment]
Yes, I'm aware of your project.

**Comment by rainwoodman** [comment]
Granularity will be a concern if the dependency is large. Spending 20mins+ to build a bundle every time will cause hardship.

**Comment by sbailey** [comment]
Perhaps this counts under option (3), but I'll note that our slow startup times are exacerbated by our current MPI-only parallelism that drives toward one startup process per core instead of one startup process per node.  If we had one MPI process startup per node and more second level parallelism (multiprocessing, cython+threads, OpenMP, etc.) then our startup times would be faster because fewer things would be starting up.  This comment doesn't matter if we use pyinstaller, shifter, or python-mpi-bcast .

**Comment by tskisner** [comment]
For @rainwoodman, bundling a huge application (much bigger than desi_pipe_run) took a couple minutes in my previous experience.  This bundling can be done as an optional install step, not every time someone does "python setup.py install".  It is only for installing versions that will be used in production.

**Comment by rainwoodman** [comment]
@tskisner I meant in the final solution, you don't want to enforce re-bundle large things like anaconda every time the application payload is updated -- depending on the filesystem status at nersc it may take up to 20mins to do so.

Otherwise even relatively complex app payload is fast to rebuild. In python-mpi-bcast we have a shortcut bcast-pip that will fetch a package from pypi or any disk location, bundle and broadcast it in the job script (it's a wrapper around pip). It's quite handy for testing development branches. I'd say it's a feature to consider having.

@sbailey One level of parallelism is already adding notable code complexity. A second level makes it more complicated.

**Comment by tskisner** [comment]
This has been solved by using docker/shifter.  Python startup time on 2048 nodes (49152 processes) loading desispec and dependencies (mpi4py, numpy, scipy, astropy, etc) takes less than a minute.
