### ISSUE TITLE
Importing redmonster during documentation builds

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#32]
Refactor the code in desispec.zfind.redmonster so that documentation can be built successfully even if redmonster is not in `$PYTHONPATH`.

**Comment by sbailey** [comment]
Good idea.  I had previously fixed the I/O code so that it wouldn't fail if redmonster wasn't available, but I hadn't realized that the documentation generation would need to load the code.  When you fix this, please post the "design pattern" for how to do this -- we will likely have other optional dependencies in the future, i.e. things that are required for a subset of the code to work but shouldn't completely break the install/docs/usage of other pieces if they don't exist.

**Comment by weaverba137** [comment]
Could you point me to that IO code?  I don't see how that happens within redmonster.py itself.

**Comment by sbailey** [comment]
It was commit https://github.com/desihub/desispec/commit/f0d90996af310f488c7fd3ec23ba250db0c02bda , though it might not apply for this case.  io.read_zfind() returns a "ZFindBase" object which was previously mixed up with the redmonster wrapper code itself.  I split those out so that the I/O code could load a ZFindBase object to create it from a file without requiring redmonster itself.

I'm imagining the solution here will be something like

    try:
        import redmonster
    except ImportError
        log.error('redmonster unavailable; docs will work but not code...')

you can refine that or develop an equivalent solution.

**Comment by weaverba137** [comment]
Indeed, it would be something like that.
