### ISSUE TITLE
Create DTS delivery scripts

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#322]
Create DTS delivery script(s) that can receive command-line arguments from DTS (easily configured in DTS configuration files) and submit pipeline processing jobs.

The script(s) should be able to handle start and end-of-night as well as routine data processing jobs.

For initial tests, use the 'desi' pseudo-user at NERSC, for a clean environment.

**Comment by weaverba137** [comment]
Another aspect of this issue: the script(s) should create or update the raw data metadatabase as needed.

**Comment by weaverba137** [comment]
Noting the connection between this ticket and #304.

**Comment by weaverba137** [comment]
The placeholder framework for pipeline start/update/end night scripts (#304) now exists, at least in preliminary form.  I now want to focus on exactly *how* the DTS delivery script will know which script to call.

My proposal is that start of night is determined at KPNO, and a specific metadata keyword signalling the start of night is passed along with the first file(s).  That is, the delivery script would have a calling signature like:

```
desi_dts_delivery $filename $night $nightState ...
```

where `nightState` would have the value `start` at the official start of night, `update` for most transfers, and `end` at the official end of night.

Also a question:  what happens if the delivery script calls `desi_update_night` and a previous call to that `desi_update_night` has not yet finished.  That is, what happens if there are multiple instances of `desi_update_night` running simultaneously?

@sbailey, @tskisner please comment.

**Comment by sbailey** [comment]
I chatted with @tskisner and the short version is that we will handle it on our end.

At the same time, it would be useful to have `desi_update_night` called only once per exposure after all files for the exposure have arrived, and not once per file.  e.g. after spectro raw data, fibermap, and GFA/ETC data have arrived, call `desi_update_night`; quicklook output syncing can happen separately independently of `desi_update_night`.

**Comment by weaverba137** [comment]
> I chatted with @tskisner and the short version is that we will handle it on our end.

Sorry, is "it" the start/update/end toggle, or handling multiple scripts run simultaneously?

I think grouping by all files associated with an exposure will be relatively easy.  Will all these files have the exposure number in the file name?  If so, then it will be very easy.

**Comment by tskisner** [comment]
Basically I'll attempt to make it such that calling those scripts in any
order at any frequency will never do any harm.  However, since we don't
intend to run the pipeline until a complete exposure is transferred over,
we don't need to call the "update" script until a whole new exposure is
transferred.  I don't know what size the data transfers are (individual
files?  whole exposures?  rsync of the night?), so not sure if this is even
an issue.

-Ted

**Comment by weaverba137** [comment]
OK, that's fine.  There are a number of modes in which DTS can be triggered, but as I just mentioned, the delivery script should be able to handle calling the update script when all files associated with an exposure have arrived.  I suppose we should use the term "collate an exposure".

**Comment by sbailey** [comment]
> Sorry, is "it" the start/update/end toggle, or handling multiple scripts run simultaneously?

"it" = handling multiple scripts run simultaneously

**Comment by weaverba137** [comment]
@sbailey, another operational question for you.

I'm very close to being able to:

1. Log in to a data transfer node as 'desi' user.
2. Run the delivery script and have it start a `desi_{start,update,end}_night` script on edison via ssh.

One final detail is what to do with output, especially log output, from the `desi_{start,update,end}_night` scripts.  Some considerations:

* The DTS delivery script should not care about any output from the  `desi_{start,update,end}_night` scripts.
* However if no special steps are taken, the output will get sent back to the data transfer node (again, via ssh).
* The best solution is if `desi_{start,update,end}_night` scripts log to a file instead of to standard output; (shell) redirecting standard output over ssh is fragile.

An additional detail: in the current "fire and forget" mode of launching the  `desi_{start,update,end}_night` scripts, is there any conceivable case where the delivery script should wait for the  `desi_{start,update,end}_night` script to finish, or can it always just run the command and immediately close the ssh connection?  Do we have even a theoretical estimate of how long the `desi_{start,update,end}_night` scripts are *supposed* to run?

**Comment by sbailey** [comment]
Agreed that the DTS delivery script should not depend upon the output for the `desi_*_night` scripts.  Sending the log output to a file instead of trying to collect it back with DTS sounds good.  

Nominally I would send these to somewhere like $SCRATCH/nightly/{YEARMMDD}/{start,update,end}-{expid}.log .  i.e. a different log file for each call to `desi_{start,update,end}_night` in case their runtimes overlap.  Logging to somewhere under `/project/projectdirs/desi/www` could also be interesting.

I don't think DTS needs to wait around for the script to finish as long as it is executed in a non-blocking way such that the connection can close without killing the process.  Normal runtimes would be just a few seconds; hiccups with SLURM or the disks could stretch that to a few minutes if something was very wrong.  These scripts will just take a peek at the disk to see what is there, do a bit of bookkeeping, then launch batch jobs to do the real work.

Ask again if that doesn't answer your question.  Glad to hear of the progress with this.

**Comment by weaverba137** [comment]
Sounds good, except for one minor detail:

> Nominally I would send these to somewhere like $SCRATCH/nightly/{YEARMMDD}/{start,update,end}-{expid}.log

The exposure id is not passed on the command line, so the night script itself would have to figure that out.  We can still *call* a night script when a particular set of files/exposures has arrived, but then it is the job of the night script to figure out which exposures it has to handle.  In any case, it will take some very careful though on how to handle logging when there could be multiple overlapping calls, and every call has to figure out everything it needs to do, given only the night.

**Comment by sbailey** [comment]
In a separate conversation, Ted has argued that `desi_update_night` doesn't need to know the exposure number.  Technically true, but I suspect that it would be handy if DTS already knows the exposure ID to go ahead and include that as an option to `desi_update_night`.

If DTS doesn't or can't know the exposure ID, then the logfiles could include a timestamp in their name to keep them sorted.  It would be very very handy if they at least were grouped by night (and if `desi_*_night` was also told the night as a clue for what to look for...)

But either way, it is our/Ted's problem to handle overlapping calls.  Let DTS just fire and forget and not get entangled in the spectro pipeline bookkeeping.

**Comment by weaverba137** [comment]
OK.  If anything it is quite easy for DTS to know and pass on the exposure ID, so that can be passed on if needed.  If nothing else, it's encoded in the filenames.
