### ISSUE TITLE
Backward-compatible Sphinx configuration

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#33]
In PR #31, the conf.py file has been changed to assume that the Sphinx Napoleon extension is installed.  This is a safe assumption for Sphinx >= 1.3.  Can we assume that everyone in DESI who wants to build documentation is already using 1.3?  For example, MacPorts has Sphinx 1.3.1.

The alternative is to include a copy of the napoleon code in desispec itself.

**Comment by sbailey** [comment]
I think that is an ok assumption.  When bringing in a new dependency, latest/recent stable version seems reasonable.  The install of the *code* shouldn't fail if sphinx is missing, but it is ok to require that if you want to build the docs, you need sphinx >= 1.3 .  It would be nice to print a friendly error message ("you need to upgrade sphinx to >= 1.3 or install the napoleon extension...") rather than just crashing out.

For the record, I have sphinx 1.2.3 based on installing last year, so I will have to upgrade...

**Comment by weaverba137** [comment]
http://sphinx-doc.org/config.html#confval-needs_sphinx shows how to set the `needs_sphinx` option.  For example, if I set it to the fictitious version 1.4, it produces the message:

```
sphinx.errors.VersionRequirementError: This project needs at least Sphinx v1.4 and therefore cannot be built with this version.
```
which seems pretty clear.

I think this test might accomplish the test for the presence of napoleon:

```python
try:
    import sphinx.ext.napoleon
    napoleon_extension = 'sphinx.ext.napoleon'
except ImportError:
    try:
        import sphinxcontrib.napoleon
        napoleon_extension = 'sphinxcontrib.napoleon'
        needs_sphinx = '1.2'
    except ImportError:
        needs_sphinx = '1.3'
```
