### ISSUE TITLE
Improve fiberflat

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#339]
Tests of desi_compute_fiberflat on teststand data and BOSS data show the code needs to be improved.
Work in progress on branch desi_on_boss by Nicolas.

**Comment by ngbusca** [comment]
Tests were failing due to small scale (~ 50A) features not being captured by the default modelling with a smoothing scale at 100 A. Lowering the default value to 20A solved the problem. 

Do we want the code to automatically adapt the smoothing scale? These small scale features are a property of the spectrograph and are unlikely to change over the course of the survey (unless the spectrograph is replaced). I think it might be an overkill for something relatively simple (i.e. the fiberflat).

**Comment by sbailey** [comment]
What you did in PR #344 is good: the smoothing resolution is an optional parameter to `compute_fiberflat`, with a default that matches what DESI needs.  We don't need the code to auto-adapt the smoothing scale.

I'm running the integration test on the desi_on_boss branch as a final check and then will merge PR #344 and close this issue.  If there are other problems that need to be fixed that weren't addressed in PR #344, please reopen this with a specific description.
