### ISSUE TITLE
Ringing on extractions for small PSF stamp size even if PSF nearly fully contained in stamp

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#340]
* desi_extract_spectra ran on teststand data with a PSF of stamp size 9x9 pix (half size 4pix) gives ringing in output spectrum. 
* ringing disappears with PSF stamp of 17x17 pix (half size 8 pix).
* but PSF is nearly fully contained in small stamp, and the two PSF models are nearly identical, so this could be a feature of the extraction and not the PSF (or we are very sensitive to PSF tails).

The following code was run. The data is at NERSC in 
```/global/homes/j/jguy/desispec-extraction-issue ```

```
desi_extract_spectra -i preproc-00000500.fits -p psf-specex-9x9.fits  --bundlesize 1 -w 5625.,7730.,1. -o frame-spectroperf-00000500-9x9.fits
desi_extract_spectra -i preproc-00000500.fits -p psf-specex-17x17.fits  --bundlesize 1 -w 5625.,7730.,1. -o frame-spectroperf-00000500-17x17.fits
plot_frame.py -f frame-spectroperf-00000500-9x9.fits frame-spectroperf-00000500-17x17.fits --fibers 12
```

![spectra](https://cloud.githubusercontent.com/assets/5192160/22747983/e07e0f9c-ee28-11e6-84a1-ba87767bfad0.png)

```
plot_psf_comparison_using_specter.py --psf1 psf-specex-9x9.fits --psf2 psf-specex-17x17.fits --fiber1 12 --fiber2 12 --wave 7100
```
![psf](https://cloud.githubusercontent.com/assets/5192160/22748248/b4209130-ee29-11e6-89c4-1fba0d424de9.png)

**Comment by sbailey** [comment]
This is a case of the wings of the PSF being off the edges of the provided spots.  Here is a zoom in of the 9x9 PSF vs. 17x17 PSF extractions.  The middle row shows the spots at the wavelengths of the ringing minima, while the bottom row shows spots at wavelengths between the minima:

![extract-ringing-spots](https://cloud.githubusercontent.com/assets/218471/22762445/360fc7e4-ee14-11e6-98be-0b683c2f4826.png)

Things of note:
  * the PSFs at the minima are hanging off the edge of the spots
  * they are considerably mis-centered
  * The actual spots provided by the code are 8x8 not 9x9 (and similarly the "17x17" spots are actually 16x16).

Fixing the size to be the quoted size and getting the centering right would significantly help, if not completely fix this.  Investigating that now...

**Comment by sbailey** [comment]
There was a specter indexing bug resulting the 8x8 instead of 9x9 PSF spot sizes.  I fixed that and pushed directly to master.  Below is the new extraction results at 3 different wavelength step sizes (0.5A, 0.75A, 1.0A), vertically offset by +-500 units for clarity.  Each pair is the comparison of the 9x9 vs. the 17x17 PSFs with very close agreement.

![extract-ringing-spots](https://cloud.githubusercontent.com/assets/218471/22765038/ed838754-ee22-11e6-97a2-438978099d00.png)

However, it appears that there is still some sort of indexing or middle-vs-edge of pixel bug: doing a scan of the spots in small wavelength steps shows that the PSF is always at the middle or above but never below.  This might be semi-harmless with small edge effects, or it could manifest itself as a 1/2 or 1 pixel offset in the wavelength solution between what was intended by the PSF and what is reported by the extractions.  Leaving this ticket open until that is either resolved or spun off into a new specter ticket.

![wavescan](https://cloud.githubusercontent.com/assets/218471/22765215/e9bb691a-ee23-11e6-84f0-788c8bd79594.png)

**Comment by sbailey** [comment]
For the notes: the specex generated PSF header says the following, which establishes the coordinate system conventions:
```
COMMENT X        : CCD column coordinate (as a function of fiber and wavelength)
COMMENT Y        : CCD row coordinate (as a function of fiber and wavelength)   
COMMENT          (X,Y)=(0,0) means that PSF is centered on center of first pixel
```

To do: verify that specter follows the same convention when interpreting this and tune the phase of how the PSF is projected into the spots.

**Comment by julienguy** [comment]
I checked the modification fixed the issue (but I leave the ticked open for study of PSF stamp centering).

**Comment by sbailey** [comment]
See desihub/specter#47 for a PR with a fix for the centering issue.  Once that is approved and merged we can close this.

**Comment by julienguy** [comment]
Fixed in specter, with a further improvement of 3% on spectral precision for 9x9 stamp psf and extraction with a step of 1A on teststand r1 data.
