### ISSUE TITLE
Which fiberassign files should be loaded?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#347]
In the December data challenge / quicksurvey example, is the database expected to hold *every* fiberassign file in `quicksurvey_example/output/dark/`, or only the last pass (4)?  For comparison, right now I am only loading the zcat file from the last pass.

**Comment by weaverba137** [comment]
PS, would it be useful to load the pass number (0-4)?  Right now I don't see where else that would appear.

**Comment by weaverba137** [comment]
Sorry for the issue creep, but I can't remember if we identified which column or combination of columns would be the primary key in the fiberassign table.

**Comment by sbailey** [comment]
This question touches on a messy aspect of the quicksurvey data challenge: The "observed" version of fiberassign that would be loaded into the DB is that last epoch in which it appears.  i.e. a fiberassign tile*.fits file can appear in multiple epochs until it is finally chosen for observation, at which point it drops from the list for future epochs.  Let's implement this as a step that organizes the "observed" version of the fiberassign files into a directory, and then separately the database load goes from whatever it finds there.

Nomenclature: the 0-4 directories in quicksurvey are "epochs" that don't have a 1:1 mapping to "passes" == "layers" in the DESI tiles file.  We don't need to load the epoch number since that can be derived from the date of observation for a tile, and we don't need to load fiber assignments for epochs in which a tile was not observed.

Loading only the final zcat is correct for now.  In the future for daily processing we'll need to handle the case of a target having a redshift/classification in the DB already, but getting updated due to more exposures of the same target.  That case won't happen for final data assemblies where everything is reprocessed from the beginning, and all possible exposures are available before redshift fitting is run.

fiberassign primary key: TILEID from HDU 1 header plus FIBER column from HDU 1 is effectively the primary key.  Note that TILEID is not in a column since it is the same for all entries in a given file, but when loading multiple fiber assignment files into a common table, the TILEID column needs to be added.

If this addresses the questions, please go ahead and close this; otherwise you can continue the discussion here.

**Comment by weaverba137** [comment]
>  Let's implement this as a step that organizes the "observed" version of the fiberassign files into a directory, and then separately the database load goes from whatever it finds there.

I can easily do this with a directory containing symlinks to the actual files.  Just to be sure: for each `<tileid>` in `<epoch>/fiberassign/tile_<tileid>.fits`, choose the version with the largest `<epoch>`, correct?

I'm already adding the tileid column, so that primary key is trivial to implement.

**Comment by weaverba137** [comment]
Actually, I don't even need to create symlinks to do this.  `glob.glob()` grabs all the tile files, then I just have to sort them by epoch and tileid.

**Comment by sbailey** [comment]
> I can easily do this with a directory containing symlinks to the actual files. Just to be sure: for each `<tileid>` in `<epoch>/fiberassign/tile_<tileid>.fits`, choose the version with the largest `<epoch>`, correct?

Correct

> Actually, I don't even need to create symlinks to do this. `glob.glob()` grabs all the tile files, then I just have to sort them by epoch and tileid.

That's ok, but be warned that in the final dataflow these will already be in a single directory; the organization by epochs is a leftover of how quicksurvey is organized and wanting to leave mid-survey results in place.  i.e. don't bake the concept of epoch into this loading code.

**Comment by weaverba137** [comment]
Got it.
