### ISSUE TITLE
desi_make_bricks fails on boss2desi

### ISSUE THREAD

**Issue by ngbusca** [desihub/desispec#360]
desi_make_bricks currently doesn't work with the output of boss2desi. 

The problem is that the latter adapts the ndiag to the resolution of the given exposure (which it's not known in advance), which results in fluctuations in ndiag (for the test plate it's between ndiag = 9 and 11). 

desi_make_bricks then fails since it expects a uniform ndiag accross exposures.

There are at least two possibilities:

* choose a "one size fits all" ndiag when constructing the desi exposures in boss2desi. We could output a warning if the code would have chosen a larger ndiag

* add a loop on desi_make_bricks to find the largest ndiag accross the exposures and use that largest ndiag for the output. 

Other ideas? Is ndiag required to be uniform across different bricks?

**Comment by sbailey** [comment]
The code using the resolution matrix doesn't require `ndiag` to be equal for everyone, but the [brick datamodel](http://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/PRODNAME/bricks/BRICKNAME/brick-CHANNEL-BRICKNAME.html) does require that since the sparse resolution matrix is stored as a 3D array with shape `[nspec,ndiag,nwave]`.

I think your second option is best: have `desi_make_bricks` detect the largest `ndiag` it needs across all exposures, and then pad smaller ones with zeros.  If that turns out to be a huge pain you could fall back to the first option of hardcoding a sufficiently large `ndiag` in boss2desi that will work for all plates.

**Comment by sbailey** [comment]
`desi_make_bricks` now uses the same `ndiag` across all exposures, thus fixing this.
