### ISSUE TITLE
resample_flux is doing odd things when extrapolating

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#414]
In the pre-2% data challenge spectra redrock was failing dramatically on QSOs, which was eventually tracked down to an issue with the templates.  Cell [9] of this notebook demonstrates the issue:
https://github.com/desihub/desisim/blob/qso-extrap/doc/nb/QSO_templates.ipynb
Notice especially the correct extrapolation of the template based on the last "measurement" but then the funny step function that drops the spectrum to zero at large wavelengths (and then back up, sometimes).

I'm using `interpolation.resample_flux` to do the interpolation, so there must be a bug there.  @julienguy did you write this code?  If so, can you please take a look when you can?

**Comment by julienguy** [comment]
This is fixed in branch "interpolate" if you use resample_flux with the option extrapolate=True.
I tested this on your QSO simulations.

see also related issue #77 also fixed in branch "interpolate"

**Comment by moustakas** [comment]
Extrapolating in this way will create problems depending on the derivative of the spectrum on the edges.  In the QSO spectrum examples your method will probably work fine because the spectra are pretty flat at long wavelengths.  

Would it be possible to simply replicate the last value (perhaps as another extrapolation option) to fill out the array?  

Note that I'm going to be experimenting with Ian's QSO templates soon at which point all the templates will have UV-mid-IR wavelength coverage, so this will no longer be an issue.

**Comment by julienguy** [comment]
John, what I did is exactly equivalent to what you are saying if I am not mistaken. You should try the code.

However, if you have some specific extrapolation needs for QSOs, it would be better that you write a custom routine better suited for your purpose. 

There are zillions of different ways to interpolate data. The specific role of resample_flux (at least when I wrote it) is to project a high resolution model spectrum on a data wavelength grid where the input spectrum is considered a piece-wise continuous flux density and the output the average flux density in bins centered on the output wavelength array (because this is what we need to interpret the data, once convolved the resolution). I added the extrapolation for convenience, but now I realize that we'd better write several 1D interpolators in interpolation.py

**Comment by moustakas** [comment]
#415 fixes this issue beautifully, thank you, @julienguy!
