### ISSUE TITLE
build_sphinx incompatible with sphinx 1.6

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#418]
As identified in PR #415, `python setup.py build_sphinx` is incompatible with sphinx 1.6.  Could we add a hook in setup.py to catch this case and immediately exit with an informative message about downgrading to 1.5 to avoid generating pages of mystery errors?  I'm thinking of something like
```
import sys
if sys.argv[1] == 'build_sphinx':
    import sphinx
    if sphinx.__version__.startswith('1.6'):
        print('build_sphinx is incompatible with sphinx version {}'.format(sphinx.__version__))
        print('please downgrade to version 1.5.x, e.g. with')
        print('    conda install sphinx=1.5')
        sys.exit(1)
```

Do we know enough about this problem to file a ticket with sphinx?

**Comment by weaverba137** [comment]
I think it is somewhat of an overstatement that `python setup.py build_sphinx` is *incompatible* with Sphinx 1.6.  The only thing I am certain of is that astropy 1.2.x and 1.3.x are incompatible with Sphinx 1.6.  This does not imply that all DESI code is incompatible.  Basically, we should move to both astropy 2.0 and Sphinx 1.6 at the same time.

**Comment by sbailey** [comment]
Then perhaps the check should be
```
import sphinx
import astropy
if sphinx.__version__.startswith('1.6') and astropy.__version__.startswith('1.'):
    ...
```
the main point is to minimize the barriers to someone running `python setup.py build_sphinx` as part of their normal routine.  When I hit sphinx errors I didn't understand, among the first things I tried was "upgrading" sphinx to 1.6 which made things much worse.  It would be preferable to informatively avoid that rather than requiring people to remember the correct combination of sphinx+astropy from these tickets.

**Comment by weaverba137** [comment]
While it is possible to do what you ask, I am very concerned that this will leave the setup.py file in a fragile state.  What may be helpful to a novice user may be painful when building in an automated environment like Travis & ReadTheDocs.  Travis is pretty forgiving because you can set up the environment almost any way you like, but ReadTheDocs stricter limits on the build environment.  And of course, at some point in the future, that code will be obsolete, will bite us, & we have to take it back out again.

I don't know what the correct solution is in this case, & I'd like to hear from more people.  @tskisner, @dkirkby, anyone else?

**Comment by moustakas** [comment]
We could just bite the bullet and require astropy>=2.0 and sphinx>=1.6 going forward.

**Comment by weaverba137** [comment]
I think we are already restricting to Sphinx < 1.6 since we haven't moved to Astropy 2.0 yet.  Will close this unless people object.

**Comment by weaverba137** [comment]
No one has objected, closing.
