### ISSUE TITLE
Improve PSF data format

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#435]
The PSF data format is not in sync between specex , specter , desispec and DESI datamodel.
 - all PSF models should have 2 HDUs for x and y legendre coefficients with the same EXTNAME keyword.
 - boot psf should have both sigmax and sigmay to be able to us it with specter if needed.
 - the specter.psf should read the bootcalib desispec psf.
 - specter.psf  should have read write I/O for trace sets for all PSFs.
 - I suggest the specter.psf should be moved to desispec to make things easier
 - the data format for specex GaussHermite should be improved
 - DESI datamodel should be synchronized.

**Comment by sbailey** [comment]
A few comments:

* desimodel/data/specpsf/psf*.fits has those x/y Legendre coefficient HDUs named XCOEFF and YCOEFF.  If that changes (in name or format) we also need to update desimodel.  That originally was a requirement of PSF formats and then became a special case exception for GaussHermite.
* Let's *not* move specter.psf into desispec so that specter can remain a self-contained experiment agnostic toolkit.
* We also have some historical cruft for GaussHermite vs. GaussHermite2 that we could cleanup.

But definitely yes, let's get these different PSF formats/codes back in sync.

**Comment by sbailey** [comment]
These were synced/fixed awhile back.  Closing ticket.
