### ISSUE TITLE
Quicklook for calibration frames

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#444]
Getting this into a ticket for tracking:

Quicklook should should be self-contained for processing arc+flat+science exposures without requiring inputs from offline processing of the same data.  In particular, quicklook should be able to generate a fiberflat from a flat (continuum) lamp exposure analogous to `desi_compute_fiberflat`, and use its own fiberflat for processing science exposures.

External inputs that quicklook *can* use:
* pre-processing calibration files, e.g. dark and biases
* initial guess of PSF shape and trace locations, e.g. desi_bootcalib output.

This issue is the last remaining piece for closing out overdue P6 activity 1836_50 "Write QL Routines".  Assigning to @rkehoe who can reassign as appropriate.

**Comment by rkehoe** [comment]
Thanks @sbailey.  This is definitely high on our list.  Currently, arc processing was implemented as discussed in the June mtg primarily by @gdhungana.  This utilizes an arc exposure to yield a QL-specific psf file.

We have the ability to make a fiber flat since August, which takes in continuum lamp exposure to yield a QL specific fiber flat output.  However, I have delayed committing this pending performance optimization work by @samikama .  If it takes much longer, I will consider committing this version and then working on speed afterwards.  

I don't think this was part of the original milestone, but for external inputs, I might suggest we should add one more.  For the fast flux calibration that is intended for QL, this will likely depend on a simplified flux calibration vector taken from offline processing.  This would then be a third area of external inputs from offline.  For the darks and biases, we develop pipelines to make those, as we will likely want QL pipelines to do QA on them each day anyways.

I will update or assign as appropriate.

**Comment by sbailey** [comment]
Kyle convinced me that it is ok for quicklook to use externally generated fiberflats thus obviating this ticket.  QL can process arcs/flats for going QA on them (good) but it no longer needs to cache those results for use by later exposures in the night (until we change our mind again...)
