### ISSUE TITLE
Create `io.download()` function.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#48]
We need a `io.download()` function to handle downloads of DESI data from the main repository.  It should:

* Be aware of the structure of the DESI repository.
* Be aware of files that have already been downloaded (*i.e.* have a cache).
* Accept a single file or list of files.

Example function signature:

```python
def download(filenames,baseurl='http://portal.nersc.gov/project/desi'):
    """Download files from DESI repository.
    """
    if isinstance(filename,str):
        filenames = [filenames]
    # ...
```

**Comment by sbailey** [comment]
We should specify if the filenames include a full local path, partial path, or no path, e.g.

  1. io.download('/local/path/spectro/redux/prodname/exposures/20150727/00000001/frame-r0-00000001.fits')
  2. io.download('exposures/20150727/00000001/frame-r0-00000001.fits')
  3. io.download('frame-r0-00000001.fits')

I tend to favor (2) so that that the same filenames list could be used to download multiple production versions, while not requiring io.download to do lookups like exposure -> night like (3) would.

Similarly, how should we specify the production name?  It might be convenient to have the filenames be given with that path relative to $DESI_SPECTRO_REDUX/$PRODNAME, while specifying the prodname as a separate argument to io.download, e.g. something like:

    io.download('path/to/blat.fits', prodname='current', baseurl='http://portal.nersc.gov/project/desi')

downloads

    http://portal.nersc.gov/project/desi/collab/spectro/redux/current/path/to/blat.fits

to local file

    $DESI_SPECTRO_REDUX/current/path/to/blat.fits
