### ISSUE TITLE
Moving General Information to One Area in Merged QA files

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#510]
QLF performance requires some general information such as lists of RA/DEC, Fiber ID, imaging magnitudes to be included in the merged yaml [eventually json] files as they are currently included but some have been repeated throughout the merged yaml file.

One argument is that QLF could independently extract these information from the input files but there is a preference that QL package these information together with the QA outputs, such as SNR, or sky continuum.
The idea is to move these lists to a "GENERAL_INFO" section for each exposure, such that any downstream processing of the merged QA file will have access to it and can combine with individual QA outputs as needed.
We propose to have this GENERAL_INFO section at the beginning of the merged yaml/json file and right below the "PIPELINE_STEPS" and at the same level as the "Metrics" section.
Removing the repeated information and placing them in one general area results in ~50% size reduction for the merged yaml files.
Please comment on this proposal as we need to implement this feature soon.

**Comment by rkehoe** [comment]
Thanks @Srheft.  This hits the important points. 

I'd like to highlight the cases where the downstream processing of merged QA files will also involve instances where input FITS files (eg. fibermap) may not be readily available, such as with QLF in the offline case or for calibration exposure validation or other tasks.  So having the crucial pieces of input information with the QAs is important. 

@profxj and @ricardogando, please comment on this proposal to improve the performance of the merged QA files.

**Comment by profxj** [comment]
I think this is a sensible approach.  Thus far I have avoided
including any such information in the offline QA.

**Comment by ricardogando** [comment]
I definitely agree. 
Other properties should go to GENERAL INFO as well 
(I would say PROGRAM, but it is currently not in mergedQA?).

To save a few bits I would also write the *_STAT flags as integers, instead of strings NORMAL, ALARM... (if too unreadable, correspondence between them could be on GENERAL INFO as well).

Format and precision of a few lists also need revision:
For plotting purposes, I think RA and Dec could be f4 arrays.
Parameters as these could be integers  NBINSHIGH: [11.0, 12.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0...

**Comment by sbailey** [comment]
Several positive comments and no complaints; green light to go ahead.  Please close this issue when it is implemented.
