### ISSUE TITLE
correction for Galactic extinction / reddening?

### ISSUE THREAD

**Issue by moustakas** [desihub/desispec#513]
In the pipeline, are the extracted spectra corrected for Galactic extinction / reddening before redshift fitting?  If so, can someone point me to the code?  If not, they should be.

**Comment by moustakas** [comment]
For the record, we have an `sfd' module in `desitarget.mock` --
  https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/sfdmap.py
although it should probably be moved to `desispec`.

**Comment by julienguy** [comment]
- The flux calibrated spectra are not (and will not) be corrected for reddening. 
- It is true we have to correct for reddening in the redshift fit. I suggest we do this in the redrock code in memory, and do not write any extra file on disk.

**Comment by moustakas** [comment]
I agree, let's move this to `redrock`, then.  But one question: how is reddening handled in flux-calibration?

**Comment by julienguy** [comment]
reddening is applied to the stellar models when deriving the calibration vector, so that the calibration vector do not include the dust extinction.
There is a routine in desispec for the dust transmission, see
https://github.com/desihub/desispec/blob/054e9ffc17142545c19354d59ed155bce09d2b70/py/desispec/scripts/stdstars.py#L83
and the extinction laws implemented in
https://github.com/desihub/desispec/blob/master/py/desispec/dustextinction.py

**Comment by moustakas** [comment]
Addressed in https://github.com/desihub/desiutil/pull/128 and https://github.com/desihub/desispec/pull/736.
