### ISSUE TITLE
2 of 7: Addition of a new QA: "CHECK_HDUs"

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#579]
Adding a QA to the beginning of the pipeline under an initial task name 'CHECK_HDUs'.  This task will check for the number of cameras written into the raw fits file.  It will match a list of cameras indicated in the template reference file to the existing cameras in the raw exposure.  The scalar metric for this QA could be a 32-bit mask where each camera sets its own bit in the HDU.  The QA then compares this word to the reference word and if any cameras differ, the difference raises a warning on the QA STATUS.  The OR of the scalar metric and its reference will be saved as a drill-down metric, such that 1 would constitute a "match" and 0 a "missmatch" that would trigger a warning.  A drill down metric will provide the list of the missing cameras.

**Comment by sbailey** [comment]
+1 for the idea of this QA, but I think making this a bitmask makes it unnecessarily complicated for users editing a config/reference file for what cameras to expect.  This is a small enough amount of data that it could just be a list of cameras in the quicklook config file, e.g. for early commissioning with only 4 spectrographs installed:
```
...
cameras = [b0, r0, z0, b1, r1, z1, b2, r2, z2, b3, r3, z3]
...
```
Then the QA code is something like:
```python
with astropy.io.fits.open(rawfile) as fx:
    for c in config['cameras']:
        if c in fx:
            # qa passed...
        else:
            # qa failed...
```

**Comment by Srheft** [comment]
Thanks for the comment @sbailey. 
The first draft of this ticket suggested to read the "CAMLIST" from the config file.
@rkehoe could weigh in on why getting the list from "the template reference file" and why the bit mask output.

**Comment by rkehoe** [comment]
I think this item was resolved over email -- we go to the camlist!

But in looking over code today another item came up tome that is vaguely similar to the 'check_hdus' idea.  In QL, there is a placeholder QA called EXPNUM_WARN, which is ultimately to be based on a corresponding BOSS flag of the same (or similar) name.  It should correspond to a check of the exposure ID given at runtime to the value in the FITS header of the input raw data file.  This is one of several possible 'data integrity' checks that are often useful.  

So this ticket seems to be a good place to ask the question, do we want this early 'check_hdus' task to only look at the camera content of the raw data file, and compare it an expected list.  Or do we ultimately see a benefit to being a bit more general so that later we can also incorporate checks for other things, like EXPID.  We shouldn't delay current tickets for these other items, but knowing if we want to allow for more generality does potentially impact how things are coded, or at least named.

Any comments?

**Comment by rkehoe** [comment]
@sbailey  et al.  Please respond to the final question in the last comment to this ticket -- should we retain the EXPNUM_WARN metric.  Right now, we are planning to reimplement it into the same QA that is checking what HDUs exist.
