### ISSUE TITLE
Real time QA analysis

### ISSUE THREAD

**Issue by ricardogando** [desihub/desispec#587]
Following Luiz da Costa and Bob Kehoe's e-mail exchange (e.g. [desi-ql-qlf-int 60]) about real time QA display on QLF I am creating this issue to discuss this idea, which was discussed at some point on QL/QLF history.

Real time QA is valuable? (maybe more during bright time)
I.e. painting petals with relevant color-coded QA information as they are available. 
If so, once (and if) per QA files are removed from QL, leaving only merged QA, should QL be able to promptly provide only the Scalar metrics in another way that does not impact performance or storage? 

Maybe a selected set of extremely straightforward QA tests should be available?
For instance,
- are fibers illuminated?

Thanks,
Ricardo

**Comment by sbailey** [comment]
If quicklook + DB loading + time to display on webapp is 2-3 minutes, then intermediate / real-time QA is low priority.  Let's get the other features fully working first (e.g. trend analysis, S/N vs. mag on QLF, summary pages of night, survey progress, etc.) before working on this.

**Comment by Srheft** [comment]
@sbailey: Agreed ... though just for the sake of clarification on where this discussion come from and why now as opposed to later: 
This discussion resurfaced today as part of a reminder that QLF should migrate from using 10 individual JSONs per camera to ONE merged JSON per camera [i.e.,  ingesting 30 JSONs per exposure as opposed to 300 JSONs per exposure]. The one night BLOB of JSONs that QL put on NERSC, contains 30 merged JSONs per exposure and we wanted to verify that this is what QLF is going to see in that BLOB and whether they are prepared for  digesting it that way.

 To my understanding, QLF [at some point in the near future] should be able get all their visualization needs from ONE merged JSON per camera and if this is not going to be enough for QLF purposes, then QL should adjust to cater to QLF needs. The functionalities exist from old discussions, they may need a dust off when QL knows what additional info and (in what output format) they should provide.

**Comment by sbailey** [comment]
Yes, loading the merged JSON means that no results can be shown for a camera until all results are available.  As long as that is <3 minutes, that is ok.  Finishing other features is higher priority than getting the first QAs displayed in <1 min.

Just checking: I'm under the impression that loading a merged JSON instead of multiple loads is to reduce the burden on the DB and thus get the *final* results displayed faster.  Correct?  Or is there some other reason?  I want to make sure that we are pursuing merged JSONs for a specific technical reason and not just because everyone thought everyone else wanted that.  For the offline pipeline, we wanted the structure to support merging multiple JSONs into a single one so that we can combine all the results into a single file per exposure to reduce the number of files on disk.  But if for some reason it would be easier for QL/F to do multiple loads, that is also fine (though we might merge them post-facto for archiving).

**Comment by rkehoe** [comment]
@ricardogando Thanks for your comments.  Please see my prior comment.  I provide some further thoughts here just for future reference:

- QL runs each QA and produces output dictionary at each step.  These outputs are the origin of the per-QA dictionaries, and the 'static plots' produced by the pipeline as it executes, if configured to output them.  

- real-time QA might be useful for longer executions (eg. calibration exposure processing), but a (near) consensus was that it was not required for science exposures, when processing is anticipated to be around 2 minutes.  Bright time exposures are even shorter and QL, so this might be the least useful place to have such a functionality.

- we have not used the qlf_ingest mechanism in a long time, so if that was a desired approach for this, it would likely require some work.

- such per-QA outputs that go the users should not duplicate the mission of the merged QA file.

- It would require a small bit of surgery to selectively only put the scalar metrics, or STATUS words, into the output dictionaries.

- in terms of tests, there is a scalar metric directed at stating whether fibers are illuminated.  This is available in the mergedQA as NGOODFIB, with corresponding STATUS.  A drill down provides the yield per fiber.
