### ISSUE TITLE
reduce preproc cosmics memory usage

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#612]
`desi_preproc` currently uses 4.6 GB of memory to pre-process a single camera.  This is dominated by the cosmics finding algorithm; using `--nocosmic` reduces the memory footprint to 1 GB.

This prevents us from preprocessing all 30 cameras in parallel on a single cori or edison node.  That's not terribly problematic for the spectro pipeline, but it could be problematic for quicklook which needs to process all 30 cameras on a single node at KPNO ASAP.  Although quicklook tests (not at NERSC) have survived full parallelism, they are likely making use of virtual memory that could be bogging down the speed.

**Comment by julienguy** [comment]
Fixed in branch light-cosmics using numba to compute gradients per pixel instead of gradient images.
 - gain of a factor 4 in memory usage (from 4GB to 1GB for the most memory consuming images which are the high S/N continuum images).
- gain in CPU time varies depending on image type. max gain is a factor 2 (from 18s to 9s to mask the cosmic rays, on a simulated dark time exposure).
