### ISSUE TITLE
Flexure modification for QL purpose

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#622]
@julienguy:
 Currently, QL only uses flexure to report the XYshifts of the traces.  A wider discussion would be whether QL should start using those PSFs [another ticket?] but for now, is it possible to turn off the PSF creation and instead spit out an array of (X,Y)shifts per fiber?

**Comment by sbailey** [comment]
We should use the shifted PSFs for quicklook, unless they turn out to be unstable with occasional catastrophic failures (which we would need to fix anyway, but they wouldn't necessarily have to cause boxcar extractions to fail).

The output PSFs should include the pre-calculated metrics for QL to use, rather than having a special mode for outputting the shifts without outputting the updated PSF itself.

Assigning to @julienguy, and I will talk to him in person since he may not have noticed this.

**Comment by julienguy** [comment]
Work in progress to run the trace shifts faster in branch faster-trace-shifts 
 - faster trace-shift along cross-dispersion (essentially thanks to a rebinning of the input image along the other axis, the dispersion axis)
- much faster boxcar extraction ( **1.5sec per frame** !!!) with numba , see
   https://github.com/desihub/desispec/blob/37449a27dcd0b09067418e3fdc56858791dee8a5/py/desispec/trace_shifts.py#L235
- the shifts of traces along x and y now takes 45s instead of 5min. 

This is still on-going work. I expect more computation time gain with a more systematic use of numba in this code

**Comment by julienguy** [comment]
Finished implementation of faster trace shifts in branch faster-trace-shifts.
For the following example run:
```time desi_compute_trace_shifts --image ~/sim2017/redux/month7/exposures/20191001/00003577/pix-r1-00003577.fits --psf ~/sim2017/redux/month7/calib2d/psf/20191001/psfnight-r1.fits --outpsf psf-shifted-dx-r1-00003577.fits```
 It now takes 20 sec compared to 3 min 30 sec with the master version on one edison core.

**Comment by julienguy** [comment]
Added header keywords in HDU PSF of the shifted PSF fits file.
Mean , min and max shifts of the traces across all fibers and the full wavelength.
For the above example (CCD r1 in a dark exposure)

```
MEANDX  = -0.00127486349305683
MINDX   = -0.04011489853837702
MAXDX   =   0.0233941410119769
MEANDY  = -0.00312482008538481
MINDY   = -0.02353019516999666
MAXDY   =   0.0116099172896611
```
(units are CCD pixels)

**Comment by julienguy** [comment]
I am closing this issue as the branch has been merged.

**Comment by sbailey** [comment]
Note to QL folks: these keywords are now min/max/mean per camera, rather than shifts per fiber.
