### ISSUE TITLE
Warning message if no raw data files found

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#651]
While testing data transfers from KPNO, we discovered that `desi_night update` was not yet "aware" of the new `NIGHT/EXPID` layout of `DESI_SPECTRO_DATA`.  However it was difficult to diagnose this, because `desi_night update` produced no output and exited with 0 exit status in this case.  If `desi_night update` is being told to find a `NIGHT/EXPID` and can't find it, it should print an error message and return a non-zero exit status.

**Comment by tskisner** [comment]
Just to be clear, having no new data is not an error condition as the pipeline is currently designed.  A user can repeatedly call the update command and jobs will only be submitted if the selected data exists AND has not already been submitted for processing.  I will add an informative message though, to make it more clear why the script is not submitting any jobs (either because no new data exists or because the job has already been submitted).

**Comment by weaverba137** [comment]
Please also make sure that a non-zero exit status is returned to the shell.  My feeling is that `desi_dts.sh` should interpret the missing files as a very, very serious error and should stop sending commands to the pipeline, and call for human investigation.

**Comment by tskisner** [comment]
Sounds good.

**Comment by weaverba137** [comment]
I believe this issue is now moot, since desitransfer is decoupled from the pipeline, and there are no plans to reintegrate. @sbailey ?

**Comment by sbailey** [comment]
Agreed.  Closing.
