### ISSUE TITLE
Does QL need to retrieve qlf-post feature?

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#700]
@rkehoe: we had a discussion on finalizing the decision on qlf_post feature in QL. How about start the discussion here and get it over with.  Please briefly enter a history of this feature and any argument on its removal or existence. Thanks.

**Comment by rkehoe** [comment]
@felipelm et al.  Coming back to this discussion from some time ago, originally QL and QLF communicated via a web interface that was provided to QL by the qlf_post function.  This was disabled some time ago in favor of file-based information exchange (the json and log file outputs), due to security concerns of the web-based interface.  However, this came up again last spring from @ricardogando but without resolution.

While there may be merits to keeping this, we are attempting to clean up some old items in QL now and would like to determine if this module can be permanently removed.  Is there any argument from the QLF side to reconsider this?  Perhaps @sbailey would like to give a final answer on this?  If possible, we would like to remove this in the current PR #707.

**Comment by felipelm** [comment]
@rkehoe talking to @ricardogando this was one attempt to get the qa status for each petal in realtime.

We are getting this information from ql log so you can remove it if you want.

**Comment by sbailey** [comment]
+1 for removing the web interface for posting the QL results and going via files instead.

**Comment by Srheft** [comment]
OK, Good. Will happen in PR#707.

**Comment by rkehoe** [comment]
Thx.  @felipelm, and @sbailey for quick response!

**Comment by rkehoe** [comment]
@srheft et al., I think we can close this ticket as it has been resolved.  Feel free to close.  Or I can do it In a bit.

**Comment by Srheft** [comment]
@rkehoe sure. is already applied in PR 707. closed.
