### ISSUE TITLE
Bitmask set/get/has?

### ISSUE THREAD

**Issue by rainwoodman** [desihub/desispec#80]
@sbailey , will you add these functions to Bitmask?

Otherwise; do you have example code segments setting masks that I can reference?

I am thinking the scenario of more than 64bits -- Is there a preferred way of dealing with that?

**Comment by sbailey** [comment]
Examples:
  * set: `mask |= ccdmask.COSMIC`
  * get: `mask & ccdmask.COSMIC`
  * has: `(mask & ccdmask.COSMIC) != 0`

During our whiteboard discussion last week I had forgotten that this works transparently for arrays of integers in addition to single integers, and even slices of those arrays, e.g.
  * `badpix = find_cosmics(image)`
  * set: `mask[badpix] |= ccdmask.COSMIC`
  * get: `mask & ccdmask.COSMIC`
  * has: `(mask & ccdmask.COSMIC) != 0`

It doesn't seem too bad for the user to do the above.  If we did add a `set` function, it is a little messy because this won't work:
```
maskbits.set(mask[badpix], ccdmask.COSMIC)
```
In this case, `mask[badpix]` is a new array not a view and the original wouldn't be updated.  We'd need to have a function signature something like `set(inputmask, masktoset, indices=None)` and catch whether inputmask is an integer or an array, whether indices is None or not, etc.  `get` and `has` are straightforwrad, but I'm not sure having them as a function is any better.  I think I prefer the boolean logic above, but you may be able to convince me otherwise.  I've been working with bitmasks long enough that my view of what is obvious and straightforward may be skewed.

More then 64 bits: let's not get fancy.  If you need more than 64 bits just start a new variable.  This keeps the code closer to what will end up in I/O files.  e.g. eBOSS targeting has EBOSS_TARGET0, EBOSS_TARGET1, ANCILLARY_TARGET0, etc.

**Comment by rainwoodman** [comment]
- Missing an equivalent of RHS 'fancy' indexing is a killer. 

- `get/set/has` functions can handle more than 64bits in an opaque way, but there is already a solution (EBOSS_TARGET1).

- Shall we consider writing down these examples and >64bit policy in docstring of maskbits ?

**Comment by rainwoodman** [comment]
Another question, if I am using masks as key in a dictionary, do you recommend using variables like ccdmask.COSMIC, or 'COSMIC'?

There doesn't seem to be a way to look up attributes(name, bitnum) of ccdmask.COSMIC.

**Comment by sbailey** [comment]
I'm not sure I understand the question, so laying out the current options for working with desispec.maskbits.BitMask objects, using ccdmask as an example:
```
from desispec.maskbits import ccdmask
ccdmask.COSMIC             #- 16  (the mask itself, not the bit number)
ccdmask.mask('COSMIC')     #- 16, equivalent to ccdmask.COSMIC
ccdmask.bitnum('COSMIC')   #- 4
ccdmask.bitname(4)         #- 'COSMIC'
ccdmask.comment('COSMIC')  #- 'Cosmic ray'
ccdmask.names()            #- ['BAD', 'HOT', 'DEAD', 'SATURATED', 'COSMIC']
```
i.e. if you have the name, you can access the bit number and mask value via `bitnum(name)` and `mask(name)`.  For that matter, if you have any of (name, bitnum, mask) you can get to the others via combinations of the above functions.  Is that what you mean by "look up attributes(name, bitnum)?  The notation of `ccdmask.COSMIC` is just syntactic sugar on `ccdmask.mask('COSMIC')`.

From the user code side, I tend to think about the fundamental entity being the name, and the bitnumber and mask are derived details.  So if you are creating a separate dictionary, I would key by name.

If that doesn't address the question, please clarify and/or let's chat in person on Monday.

**Comment by rainwoodman** [comment]
Thanks for the explanation. I think my confusion rises from that ccdmask.COSMIC does not resolve to the fundamental entity but is an alias to a derived attribute. 

Given that I haven't been biased towards the traditional SDSS code base, the following would have felt more intuitive to me:

```
assert ccdmask.COSMIC.name == "COSMIC"
assert ccdmask.COSMIC.bitnum == 4
assert ccdmask.COSMIC.bitmask == 16
assert hash(ccdmask.COSMIC) == ccdmask.COSMIC.name

# and as a shortcut,
assert 0 | ccdmask.COSMIC == 16
```

Anyhow, this is just a minor point. The current code does not lack any functionality - I will just use string name as keys. But I would still add the set/get/has example you had to the docstring.
