### ISSUE TITLE
R4 fiberflatnight mask issues

### ISSUE THREAD

**Issue by zkdtc** [desihub/desispec#897]
I have traced down the reason of weird r4 fiberflatnight mask at two wavelength ends. They are marked because their values are greater than 2, almost 3. The reason they are so large is that the code ‘desi_autocalib_fiberflat’ assumes all spectrographs have the same mean spectrum to make a correction, but r4 has a very different mean spec than other spectrographs, especially at the two ends (shown in left panel below). If the assumption is correct, then we should accept the ~3 fiber flat for r4 by increasing the masking threshold. However, I am not sure if the assumption is correct, because the code uses 4 individual fiber flats to combine one master fiber flat, but the mean spectra of the last exposures (r4 exp3 in the right panel below) are very different around 6750A, which makes no sense to me. 
![r4_fiberflatnight_mask](https://user-images.githubusercontent.com/26392765/75719090-f2fa0280-5c88-11ea-8f9a-c6b9ddac3369.png)

**Comment by zkdtc** [comment]
Could the very different spectral shape because of a missing LED? I trace back to 20191115 with the oldest fiberflatnight, it is the same, as shown below. 

![Screen Shot 2020-03-10 at 2 36 06 PM](https://user-images.githubusercontent.com/26392765/76362915-3387fa80-62df-11ea-93cd-a5b087afe64a.png)

**Comment by julienguy** [comment]
It's possible one the LED is very faint in one box. We see it's stable with time so that's a good thing.
The fact the lamps have different spectra is not an issue because the fiber flats are determined independently for each lamp (and the signal in each fiber divided by the mean spectrum of the same exposure, which is with one lamp). This is precisely the purpose of this procedure where we illuminate the white spot with one lamp at a time.
Now you are correct we should change the masking threshold when we are averaging the fiberflats obtained with all spectrographs.

**Comment by julienguy** [comment]
Fixed into master:
do not mask fiberflat >2 or <0.1 in routine autocalib_fiberflat because the fiberflat includes the throughput difference between spectrographs.
