### ISSUE TITLE
spectra files with separated cameras

### ISSUE THREAD

**Issue by julienguy** [desihub/desispec#914]
Add to the automated pipeline the spectra files , not coadded, with the cameras separated.
This is a request of the MWS group.

**Comment by segasai** [comment]
I  guess here there are two requests. 
1) We would like to see spectra-64 like files for individual exposures, so I wouldn't have to fake them myself, by gluing together the cframes.
2) The second one is a bit of a wish, is that we'd prefer to have coadd as 3 separate arms rather than glued together. That makes more sense from modeling point of view and also matches exactly individual exposure format, so we don't have to have a separate code path, separate set of spectral templates generated etc.

**Comment by moustakas** [comment]
Coadded spectra separated by camera would also be useful from the perspective of the GQP working group.

**Comment by callendeprieto** [comment]
Just to add that there are sound reasons to avoid merging the arms, and those led to the original format in the spectra-64 files. We should try to stick to the same format in the coadds, for consistency and simplicity. If required the merged array could be included in an additional HDU?

**Comment by akremin** [comment]
All requests have been completed in PR #945
