### ISSUE TITLE
odd spectrum (with high redrock RCHI2DIFF)

### ISSUE THREAD

**Issue by janewman-pitt-edu** [desihub/desispec#969]
I think this is probably a desispec not redrock problem, so putting this here.

Target ID 35185923939371730 exhibits a large negative flux around 8450 angstroms which is driving the redshift fit, with a large RCHI2DIFF.  The feature is not quite around a sky line (there are some other regions of highly negative flux that do correspond to sky features).  

A redrock kludge that might help is limiting contributions of negative fluxes to chi-squared (e.g., treating them as zero in the computation), though that could lead to biases.

If  2D images of spectra + residuals were available in prospect it would be a lot easier to tell what's going on here :) 

<img width="1518" alt="Screen Shot 2020-05-20 at 12 51 31 PM" src="https://user-images.githubusercontent.com/3122485/82474548-2f274d00-9a99-11ea-8604-1df7f13ee182.png">

**Comment by julienguy** [comment]
This feature is not present any more in the most recent "development" reduction thanks to the new pixmask `pixmask-sm4-z-20201014.fits` from @biprateep (second issue fixed with this contribution).
![Screenshot from 2020-10-28 15-35-37](https://user-images.githubusercontent.com/5192160/97504100-7f051c80-1933-11eb-9cd6-eb3a988dc2b1.png)

See for instance
```
plot_frame -i /global/cfs/cdirs/desi/spectro/redux/{andes,jguy}/exposures/20200315/00055626/cframe-z0-00055626.fits --fiber 373
```
![Screenshot from 2020-10-28 15-42-00](https://user-images.githubusercontent.com/5192160/97504494-36019800-1934-11eb-9c3c-3a8a93f70c6f.png)
