### ISSUE TITLE
Large negative flux around 5500 Angstrom in Andes data

### ISSUE THREAD

**Issue by jsuarez314** [desihub/desispec#983]
We explored the observations from the night of 14-03-2020 included in the ANDES Data Release. We used the flux of 22K objects as input for the UMAP algorithm. We explored this map and found some outliers in the embedding. Plotting the spectra we find a large negative flux around 5500 Angstrom. Below are the plots for all the outliers. The plots show the TILE, NIGHT, PETAL and TARGETID.

The TARGETID for these objects are:
[611646930002378807, 611646930006574018, 35190944424790504, 35190949411817627, 35190954377871803, 35185766799769607, 35185766803968039, 35191181935645212, 35191186020896571, 35185766116098370, 35185766120297470, 35185772160092167, 35191266723497398, 35191270368346796, 35191270368348426]

![ANDES_DR_20200314](https://user-images.githubusercontent.com/3946766/84336007-ee809800-ab5b-11ea-9b07-ead985ef64d4.png)

**Comment by julienguy** [comment]
This dip was due to a defect in the CCD that is now masked (in file `pixmask-sm10-b-20201014.fits`). I have checked that for a few spectra, not all of them.
Fibers affected where fibers 708-7011 included.

![Screenshot from 2020-10-28 11-40-53](https://user-images.githubusercontent.com/5192160/97482154-05f5cd00-1913-11eb-894f-eadd099a241f.png)

```
plot_frame -i /global/homes/j/jguy/redux/{andes,jguy}/exposures/20200314/00055456/sframe-b1-00055456.fits --fiber 710
```
![Screenshot from 2020-10-28 11-43-35](https://user-images.githubusercontent.com/5192160/97482204-19a13380-1913-11eb-9680-9f91e9ca2070.png)
